import { Platform, StyleSheet } from 'react-native';

import {
    FULL_PLAYER_ARTWORK_SIZE,
    FULL_PLAYER_PADDING_BOTTOM,
    FULL_PLAYER_PADDING_TOP,
    HOME_COMPACT_OFFSET,
    HOME_EDGE_PADDING,
    HOME_PRIMARY_TILE,
    HOME_ROUNDED_OFFSET,
    HOME_TILE_GAP,
    MINI_PLAYER_ARTWORK_SIZE,
    MINI_PLAYER_BOTTOM,
    MINI_PLAYER_HEIGHT,
    MINI_PLAYER_RADIUS,
    MINI_PLAYER_VERTICAL_PADDING,
    QUEUE_SHEET_HEIGHT,
    SCREEN_HEIGHT,
    SCREEN_WIDTH,
    VIEW_ALL_SIDEBAR_GUTTER,
    VIEW_ALL_TILE_HEIGHT,
    VIEW_ALL_TILE_SIZE,
} from './layout';
import { colors, spacing } from './tokens';

export const styles = StyleSheet.create({
    addRadioActions: {
        gap: spacing.sm,
        marginTop: spacing.sm,
    },
    addRadioForm: {
        paddingBottom: spacing.lg,
    },
    addRadioLabel: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '800',
        letterSpacing: 0.4,
        marginTop: spacing.md,
        textTransform: 'uppercase',
    },
    addRadioThumbnailButton: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: 8,
        height: 36,
        justifyContent: 'center',
        paddingHorizontal: spacing.sm,
    },
    addRadioThumbnailButtonText: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '800',
    },
    addRadioThumbnailImage: {
        height: '100%',
        width: '100%',
    },
    addRadioThumbnailMeta: {
        flex: 1,
        minWidth: 0,
    },
    addRadioThumbnailPicker: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 8,
        flexDirection: 'row',
        gap: spacing.sm,
        marginTop: spacing.sm,
        minHeight: 64,
        padding: 8,
    },
    addRadioThumbnailPreview: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: 6,
        height: 48,
        justifyContent: 'center',
        overflow: 'hidden',
        width: 48,
    },
    addRadioThumbnailSubtitle: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '600',
        lineHeight: 16,
        marginTop: 2,
    },
    addRadioThumbnailTitle: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '800',
    },
    addRadioServerBlock: {
        marginBottom: spacing.xs,
    },
    addRadioServerPill: {
        alignItems: 'center',
        borderColor: 'rgba(255,255,255,0.10)',
        borderRadius: 999,
        borderWidth: 1,
        marginRight: spacing.sm,
        maxWidth: 180,
        paddingHorizontal: spacing.md,
        paddingVertical: 9,
    },
    addRadioServerPillActive: {
        backgroundColor: 'rgba(202,160,79,0.16)',
        borderColor: 'rgba(202,160,79,0.45)',
    },
    addRadioServerPillText: {
        color: colors.muted,
        fontSize: 13,
        fontWeight: '700',
    },
    addRadioServerPillTextActive: {
        color: colors.accent,
    },
    addRadioSheet: {
        backgroundColor: '#000000',
        borderColor: 'rgba(255,255,255,0.06)',
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        borderTopWidth: StyleSheet.hairlineWidth,
        maxHeight: '88%',
        paddingBottom: 24,
        paddingHorizontal: spacing.lg,
        paddingTop: 8,
    },
    addRadioSuccess: {
        color: colors.accent,
        fontSize: 13,
        fontWeight: '700',
        lineHeight: 18,
        marginTop: spacing.md,
    },
    actionSheet: {
        backgroundColor: '#000000',
        borderColor: 'rgba(255,255,255,0.06)',
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        borderTopWidth: StyleSheet.hairlineWidth,
        paddingBottom: 36,
        paddingTop: 8,
    },
    actionSheetCancelRow: {
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.04)',
        borderRadius: 14,
        height: 52,
        justifyContent: 'center',
        marginHorizontal: spacing.lg,
        marginTop: 12,
    },
    actionSheetCancelText: {
        color: colors.text,
        fontSize: 16,
        fontWeight: '600',
    },
    actionSheetHandle: {
        alignSelf: 'center',
        backgroundColor: 'rgba(255,255,255,0.22)',
        borderRadius: 999,
        height: 4,
        marginTop: 8,
        width: 38,
    },
    actionSheetRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 16,
        minHeight: 56,
        paddingHorizontal: spacing.lg,
    },
    actionSheetRowIcon: {
        alignItems: 'center',
        height: 28,
        justifyContent: 'center',
        width: 28,
    },
    actionSheetRowText: {
        color: colors.text,
        flex: 1,
        fontSize: 16,
        fontWeight: '500',
    },
    actionSheetSeparator: {
        backgroundColor: 'rgba(255,255,255,0.05)',
        height: StyleSheet.hairlineWidth,
        marginHorizontal: spacing.lg,
    },
    actionSheetSongSubtitle: {
        color: colors.muted,
        fontSize: 13,
        paddingBottom: 16,
        paddingHorizontal: spacing.lg,
        textAlign: 'center',
    },
    actionSheetSongTitle: {
        color: colors.text,
        fontSize: 16,
        fontWeight: '700',
        paddingBottom: 4,
        paddingHorizontal: spacing.lg,
        paddingTop: 12,
        textAlign: 'center',
    },
    actionSheetTitle: {
        color: 'rgba(255,255,255,0.55)',
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 0.6,
        paddingBottom: 10,
        paddingHorizontal: spacing.lg,
        paddingTop: 18,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    artworkZoomCloseButton: {
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.10)',
        borderRadius: 999,
        height: 44,
        justifyContent: 'center',
        position: 'absolute',
        right: spacing.lg,
        top: Platform.OS === 'android' ? 42 : 24,
        width: 44,
    },
    artworkZoomImage: {
        height: '100%',
        width: '100%',
    },
    artworkZoomImageFrame: {
        alignSelf: 'center',
        aspectRatio: 1,
        borderRadius: 4,
        overflow: 'hidden',
        width: SCREEN_WIDTH - spacing.lg * 2,
    },
    artworkZoomModal: {
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.94)',
        flex: 1,
        justifyContent: 'center',
    },
    outputPickerEmpty: {
        color: colors.muted,
        fontSize: 14,
        lineHeight: 19,
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.md,
    },
    outputPickerError: {
        color: '#ff9a8a',
        fontSize: 13,
        lineHeight: 18,
        paddingHorizontal: spacing.lg,
        paddingTop: spacing.sm,
    },
    outputPickerIcon: {
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.07)',
        borderColor: 'rgba(255,255,255,0.08)',
        borderRadius: 18,
        borderWidth: StyleSheet.hairlineWidth,
        height: 36,
        justifyContent: 'center',
        width: 36,
    },
    outputPickerIconLabel: {
        color: colors.text,
        fontSize: 11,
        fontWeight: '900',
        lineHeight: 13,
        maxWidth: 28,
        textAlign: 'center',
    },
    outputPickerIconLabelSelected: {
        color: colors.accent,
    },
    outputPickerIconSelected: {
        backgroundColor: 'rgba(202,160,79,0.16)',
        borderColor: 'rgba(202,160,79,0.34)',
    },
    outputPickerList: {
        paddingBottom: spacing.sm,
    },
    outputPickerLoading: {
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 120,
    },
    outputPickerScroll: {
        maxHeight: 430,
    },
    outputPickerRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 12,
        minHeight: 60,
        paddingHorizontal: spacing.lg,
        paddingVertical: 8,
    },
    outputPickerRowBody: {
        flex: 1,
        minWidth: 0,
    },
    outputPickerRowDisabled: {
        opacity: 0.48,
    },
    outputPickerRowPressed: {
        backgroundColor: 'rgba(255,255,255,0.05)',
    },
    outputPickerRowSelected: {
        backgroundColor: 'rgba(202,160,79,0.08)',
    },
    outputPickerSectionLabel: {
        color: 'rgba(255,255,255,0.42)',
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 0,
        paddingHorizontal: spacing.lg,
        paddingTop: spacing.md,
        textTransform: 'uppercase',
    },
    outputPickerState: {
        alignItems: 'center',
        height: 28,
        justifyContent: 'center',
        width: 28,
    },
    outputPickerSubtitle: {
        color: colors.muted,
        fontSize: 13,
        marginTop: 2,
    },
    outputPickerTitle: {
        color: colors.text,
        fontSize: 16,
        fontWeight: '600',
    },
    albumHero: {
        alignItems: 'center',
        marginBottom: spacing.lg,
        marginTop: spacing.lg,
        position: 'relative',
    },
    albumHeroActions: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
    },
    albumHeroActionsBar: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: spacing.md,
        width: '100%',
    },
    albumHeroArtwork: {
        aspectRatio: 1,
        backgroundColor: colors.surface,
        borderRadius: 4,
        width: Math.min(SCREEN_WIDTH - HOME_EDGE_PADDING * 2 - 40, 360),
    },
    albumHeroArtworkFallback: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    albumHeroArtworkWrap: {
        marginBottom: spacing.md,
        position: 'relative',
    },
    albumHeroBadgeRow: {
        alignItems: 'center',
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        justifyContent: 'center',
        marginBottom: 6,
    },
    albumHeroEyebrow: {
        color: colors.accent,
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 1.4,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    albumHeroGlyphButton: {
        alignItems: 'center',
        borderRadius: 999,
        height: 44,
        justifyContent: 'center',
        width: 44,
    },
    albumHeroLeftActions: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
    },
    albumHeroMeta: {
        alignItems: 'center',
        marginTop: spacing.xs,
        width: '100%',
    },
    albumHeroMetaLine: {
        color: colors.muted,
        fontSize: 13,
        fontWeight: '600',
        lineHeight: 18,
        textAlign: 'center',
    },
    albumHeroMetaRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.md,
        marginTop: spacing.xs,
        width: '100%',
    },
    albumHeroMetaText: {
        flex: 1,
        minWidth: 0,
    },
    albumHeroPlayButton: {
        backgroundColor: colors.accent,
        height: 52,
        width: 52,
    },
    albumHeroTitle: {
        color: colors.text,
        fontSize: 26,
        fontWeight: '900',
        letterSpacing: 0,
        lineHeight: 30,
        marginBottom: spacing.sm,
        textAlign: 'center',
    },
    albumDiscHeader: {
        borderTopColor: 'rgba(255,255,255,0.08)',
        borderTopWidth: StyleSheet.hairlineWidth,
        marginTop: spacing.md,
        paddingBottom: spacing.xs,
        paddingTop: spacing.md,
    },
    albumDiscHeaderText: {
        color: colors.accent,
        fontSize: 12,
        fontWeight: '900',
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    albumTrackNumber: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 28,
    },
    albumTrackNumberText: {
        color: colors.muted,
        fontSize: 15,
        fontVariant: ['tabular-nums'],
        fontWeight: '700',
    },
    alphabetSidebar: {
        alignItems: 'center',
        bottom: MINI_PLAYER_BOTTOM + MINI_PLAYER_HEIGHT + spacing.sm,
        justifyContent: 'center',
        position: 'absolute',
        right: 0,
        top: spacing.sm,
        width: 34,
        zIndex: 4,
    },
    alphabetSidebarRail: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 4,
    },
    alphabetSidebarLetter: {
        color: 'rgba(255,255,255,0.18)',
        fontSize: 10,
        fontWeight: '800',
        letterSpacing: 0,
    },
    alphabetSidebarLetterActive: {
        color: colors.accent,
    },
    alphabetSidebarLetterButton: {
        alignItems: 'center',
        height: 14,
        justifyContent: 'center',
        width: 32,
    },
    appIcon: {
        height: 34,
        resizeMode: 'contain',
        width: 34,
    },
    appIconButton: {
        alignItems: 'center',
        backgroundColor: 'transparent',
        borderRadius: 8,
        height: 44,
        justifyContent: 'center',
        width: 44,
    },
    artistAlbumGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginTop: spacing.md,
    },
    artistAlbumGridArtwork: {
        aspectRatio: 1,
        borderRadius: 6,
        width: '100%',
    },
    artistAlbumGridFallback: {
        alignItems: 'center',
        aspectRatio: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.07)',
        borderRadius: 6,
        justifyContent: 'center',
        width: '100%',
    },
    artistAlbumGridItem: {
        position: 'relative',
        width: '30%',
    },
    artistAlbumGridTitle: {
        color: colors.text,
        fontSize: 12,
        fontWeight: '700',
        marginTop: 5,
    },
    artistBio: {
        color: colors.muted,
        fontSize: 14,
        lineHeight: 20,
    },
    artistBioToggle: {
        color: colors.accent,
        fontSize: 13,
        fontWeight: '700',
        marginTop: spacing.xs,
    },
    artworkImageFallback: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.07)',
        justifyContent: 'center',
    },
    bookInfoArtwork: {
        backgroundColor: '#2a2a2c',
        borderRadius: 12,
        height: 188,
        width: 188,
    },
    bookInfoArtworkFallback: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    bookInfoArtworkWrap: {
        alignItems: 'center',
        marginBottom: spacing.lg,
        shadowColor: '#000',
        shadowOffset: { height: 12, width: 0 },
        shadowOpacity: 0.4,
        shadowRadius: 22,
    },
    bookInfoAuthor: {
        color: colors.muted,
        fontSize: 15,
        fontWeight: '600',
        marginTop: 4,
        textAlign: 'center',
    },
    bookInfoBackdrop: {
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.78)',
        bottom: 0,
        flex: 1,
        justifyContent: 'center',
        left: 0,
        paddingHorizontal: spacing.lg,
        position: 'absolute',
        right: 0,
        top: 0,
    },
    bookInfoCloseButton: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        borderRadius: 12,
        marginHorizontal: spacing.lg,
        marginVertical: spacing.md,
        paddingVertical: 14,
    },
    bookInfoCloseLabel: {
        color: colors.text,
        fontSize: 15,
        fontWeight: '800',
        letterSpacing: 0.2,
    },
    bookInfoDescription: {
        color: '#d8d8d8',
        fontSize: 14,
        fontWeight: '400',
        lineHeight: 21,
    },
    bookInfoEmpty: {
        color: colors.muted,
        fontSize: 13,
        marginTop: spacing.md,
        textAlign: 'center',
    },
    bookInfoError: {
        color: '#ff7a6e',
        fontSize: 13,
        fontWeight: '700',
        marginTop: spacing.md,
        textAlign: 'center',
    },
    bookInfoEyebrow: {
        color: colors.accent,
        fontSize: 10,
        fontWeight: '900',
        letterSpacing: 1.4,
        marginBottom: 6,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    bookInfoLoading: {
        marginTop: spacing.lg,
    },
    bookInfoMetadata: {
        alignItems: 'center',
        gap: 2,
        marginBottom: spacing.lg,
        marginTop: spacing.md,
    },
    bookInfoMetadataLine: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '600',
        letterSpacing: 0.2,
        textAlign: 'center',
    },
    bookInfoScrollContent: {
        padding: spacing.lg,
        paddingBottom: spacing.md,
    },
    bookInfoSectionTitle: {
        color: colors.accent,
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 1.2,
        marginBottom: 8,
        textTransform: 'uppercase',
    },
    bookInfoSheet: {
        backgroundColor: 'rgba(20, 20, 22, 0.985)',
        borderColor: 'rgba(255, 255, 255, 0.07)',
        borderRadius: 22,
        borderWidth: 0.5,
        elevation: 22,
        maxHeight: '82%',
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { height: 18, width: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 30,
        width: '100%',
    },
    bookInfoTitle: {
        color: colors.text,
        fontSize: 22,
        fontWeight: '900',
        letterSpacing: 0.1,
        lineHeight: 27,
        textAlign: 'center',
    },
    castGlyph: {
        borderRadius: 3,
        borderWidth: 1.8,
        height: 18,
        position: 'relative',
        width: 23,
    },
    castGlyphDot: {
        borderRadius: 2,
        bottom: 2,
        height: 4,
        left: 2,
        position: 'absolute',
        width: 4,
    },
    castGlyphWaveLarge: {
        borderBottomLeftRadius: 13,
        borderBottomWidth: 1.8,
        borderLeftWidth: 1.8,
        bottom: 2,
        height: 13,
        left: 2,
        position: 'absolute',
        width: 13,
    },
    castGlyphWaveSmall: {
        borderBottomLeftRadius: 8,
        borderBottomWidth: 1.8,
        borderLeftWidth: 1.8,
        bottom: 2,
        height: 8,
        left: 2,
        position: 'absolute',
        width: 8,
    },
    clearGlyph: {
        alignItems: 'center',
        height: 18,
        justifyContent: 'center',
        position: 'relative',
        width: 18,
    },
    clearGlyphStroke: {
        borderRadius: 999,
        height: 2,
        position: 'absolute',
        width: 14,
    },
    connectedServers: {
        gap: spacing.sm,
        marginTop: spacing.md,
    },
    content: {
        // tabBar (~62) + miniPlayer (~78) + breathing room
        paddingBottom: 200,
        paddingHorizontal: HOME_EDGE_PADDING,
        paddingTop: spacing.lg,
    },
    contextMenu: {
        backgroundColor: 'rgba(18, 18, 18, 0.96)',
        borderColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 12,
        borderWidth: 1,
        bottom: 26,
        left: spacing.lg,
        maxHeight: '62%',
        padding: spacing.md,
        position: 'absolute',
        right: spacing.lg,
    },
    contextMenuBackdrop: {
        backgroundColor: 'rgba(0, 0, 0, 0.42)',
        bottom: 0,
        left: 0,
        position: 'absolute',
        right: 0,
        top: 0,
    },
    contextMenuError: {
        color: '#ffb1a3',
        fontSize: 12,
        fontWeight: '700',
        lineHeight: 16,
        marginTop: spacing.sm,
    },
    contextMenuEyebrow: {
        color: colors.accent,
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 0,
        marginBottom: 4,
        textTransform: 'uppercase',
    },
    contextMenuList: {
        marginTop: spacing.sm,
    },
    contextMenuRow: {
        alignItems: 'center',
        borderColor: colors.border,
        borderTopWidth: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        minHeight: 48,
        paddingVertical: spacing.sm,
    },
    contextMenuRowText: {
        color: colors.text,
        flex: 1,
        fontSize: 15,
        fontWeight: '800',
        lineHeight: 19,
        marginRight: spacing.sm,
    },
    contextMenuSuccess: {
        color: colors.accent,
        fontSize: 12,
        fontWeight: '800',
        lineHeight: 16,
        marginTop: spacing.sm,
    },
    contextMenuTitle: {
        color: colors.text,
        fontSize: 19,
        fontWeight: '900',
        lineHeight: 24,
    },
    continueProgressFill: {
        backgroundColor: colors.accent,
        borderRadius: 999,
        height: '100%',
    },
    continueProgressTrack: {
        backgroundColor: 'rgba(255, 255, 255, 0.16)',
        borderRadius: 999,
        height: 4,
        marginTop: spacing.sm,
        overflow: 'hidden',
        width: '100%',
    },
    detailArtwork: {
        aspectRatio: 1,
        backgroundColor: colors.surface,
        borderRadius: 8,
        width: 132,
    },
    detailArtworkFallback: {
        alignItems: 'center',
        aspectRatio: 1,
        backgroundColor: colors.surface,
        borderRadius: 8,
        justifyContent: 'center',
        width: 132,
    },
    detailArtworkRound: {
        borderRadius: 999,
    },
    detailHero: {
        alignItems: 'flex-start',
        flexDirection: 'row',
        gap: spacing.md,
        marginTop: spacing.lg,
    },
    detailCollapsedActions: {
        alignItems: 'center',
        elevation: 3,
        flexDirection: 'row',
        gap: 10,
        position: 'absolute',
        right: HOME_EDGE_PADDING,
        zIndex: 3,
    },
    detailCollapsedBackButton: {
        alignItems: 'center',
        borderRadius: 999,
        height: 42,
        justifyContent: 'center',
        left: HOME_EDGE_PADDING - 8,
        position: 'absolute',
        width: 42,
        zIndex: 2,
    },
    detailCollapsedBackGlyph: {
        color: colors.text,
        fontSize: 36,
        fontWeight: '300',
        includeFontPadding: false,
        lineHeight: 40,
        marginTop: -2,
    },
    detailCollapsedIconButton: {
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.08)',
        borderRadius: 999,
        height: 42,
        justifyContent: 'center',
        width: 42,
    },
    detailCollapsedPlayButton: {
        alignItems: 'center',
        backgroundColor: colors.accent,
        borderRadius: 999,
        height: 42,
        justifyContent: 'center',
        width: 42,
    },
    detailCollapsedTitle: {
        color: colors.text,
        fontSize: 17,
        fontWeight: '900',
        letterSpacing: 0,
        lineHeight: 21,
        textAlign: 'center',
    },
    detailCollapsedTitleWrap: {
        left: HOME_EDGE_PADDING + 48,
        minWidth: 0,
        position: 'absolute',
        right: HOME_EDGE_PADDING + 112,
    },
    detailCollapsedTopbar: {
        alignItems: 'center',
        height: 58,
        justifyContent: 'center',
        left: 0,
        position: 'absolute',
        right: 0,
        top: 0,
        zIndex: 20,
    },
    detailCollapsedTopbarBackdrop: {
        backgroundColor: 'rgba(0, 0, 0, 0.92)',
        borderBottomColor: 'rgba(255, 255, 255, 0.06)',
        borderBottomWidth: StyleSheet.hairlineWidth,
        bottom: 0,
        left: 0,
        position: 'absolute',
        right: 0,
        top: 0,
    },
    detailHeroActions: {
        alignSelf: 'flex-end',
        flexDirection: 'row',
        gap: spacing.sm,
        justifyContent: 'flex-end',
        marginTop: spacing.md,
    },
    detailHeroText: {
        flex: 1,
    },
    mediaDetailContent: {
        paddingBottom: 200,
        paddingHorizontal: HOME_EDGE_PADDING,
        paddingTop: 58,
    },
    mediaDetailScreen: {
        backgroundColor: colors.background,
        flex: 1,
    },
    detailPlayPill: {
        alignItems: 'center',
        backgroundColor: colors.accent,
        borderRadius: 999,
        flexDirection: 'row',
        gap: 8,
        height: 44,
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    detailPlayPillText: {
        color: colors.background,
        fontSize: 15,
        fontWeight: '900',
    },
    detailShufflePill: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: 'rgba(255,255,255,0.1)',
        borderRadius: 999,
        borderWidth: 1,
        flexDirection: 'row',
        gap: 8,
        height: 44,
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    detailShufflePillText: {
        color: colors.text,
        fontSize: 15,
        fontWeight: '800',
    },
    detailTitle: {
        color: colors.text,
        fontSize: 24,
        fontWeight: '900',
        lineHeight: 28,
        marginBottom: spacing.xs,
    },
    detailType: {
        color: colors.accent,
        fontSize: 12,
        fontWeight: '800',
        marginBottom: spacing.xs,
        textTransform: 'capitalize',
    },
    disabledButton: {
        opacity: 0.45,
    },
    downCaretGlyph: {
        height: 20,
        position: 'relative',
        width: 24,
    },
    downCaretStroke: {
        borderRadius: 999,
        height: 2.4,
        position: 'absolute',
        top: 9,
        width: 13,
    },
    downCaretStrokeLeft: {
        left: 2,
        transform: [{ rotate: '42deg' }],
    },
    downCaretStrokeRight: {
        right: 2,
        transform: [{ rotate: '-42deg' }],
    },
    downloadActionButton: {
        paddingHorizontal: 8,
        paddingVertical: 6,
    },
    downloadActionDestructive: {
        color: '#ff7a6e',
    },
    downloadActionLabel: {
        color: colors.text,
        fontSize: 11,
        fontWeight: '700',
    },
    downloadGroup: {
        backgroundColor: colors.surface,
        borderRadius: 10,
        marginTop: spacing.sm,
        padding: spacing.sm,
    },
    downloadGroupArtwork: {
        backgroundColor: '#2a2a2c',
        borderRadius: 6,
        height: 40,
        width: 40,
    },
    downloadGroupArtworkFallback: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    downloadGroupHeader: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 10,
        marginBottom: 6,
    },
    downloadGroupSubtitle: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: '600',
        textTransform: 'capitalize',
    },
    downloadGroupText: {
        flex: 1,
    },
    downloadGroupTitle: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '800',
    },
    downloadProgressFill: {
        backgroundColor: colors.accent,
        height: 3,
    },
    downloadProgressTrack: {
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        borderRadius: 2,
        height: 3,
        marginTop: 4,
        overflow: 'hidden',
    },
    downloadRow: {
        alignItems: 'center',
        flexDirection: 'row',
        paddingVertical: 8,
    },
    downloadRowActions: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 4,
    },
    downloadRowStatus: {
        color: colors.muted,
        fontSize: 11,
        marginTop: 2,
    },
    downloadRowText: {
        flex: 1,
    },
    downloadRowTitle: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '700',
    },
    downloadsStorageActions: {
        flexWrap: 'wrap',
        flexDirection: 'row',
        gap: spacing.sm,
        marginTop: spacing.sm,
    },
    downloadsStorageButton: {
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderColor: 'rgba(255, 255, 255, 0.12)',
        borderRadius: 8,
        borderWidth: 1,
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    downloadsStorageButtonLabel: {
        color: colors.text,
        fontSize: 12,
        fontWeight: '700',
    },
    downloadsStorageLabel: {
        color: colors.accent,
        fontSize: 10,
        fontWeight: '900',
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    downloadsStorageNote: {
        color: colors.muted,
        fontSize: 11,
        marginTop: 6,
    },
    downloadsStorageRow: {
        backgroundColor: colors.surface,
        borderRadius: 10,
        marginBottom: spacing.md,
        padding: spacing.md,
    },
    downloadsStorageValue: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '700',
        marginTop: 4,
    },
    downloadsSummary: {
        color: colors.muted,
        fontSize: 13,
        lineHeight: 18,
        marginBottom: spacing.md,
        marginTop: spacing.xs,
    },
    errorBoundaryButton: {
        backgroundColor: colors.accent,
        borderRadius: 999,
        marginTop: spacing.md,
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.sm,
    },
    errorBoundaryButtonText: {
        color: '#050505',
        fontSize: 15,
        fontWeight: '800',
    },
    errorBoundaryRoot: {
        alignItems: 'center',
        backgroundColor: colors.background,
        flex: 1,
        justifyContent: 'center',
        padding: spacing.lg,
    },
    errorBoundarySubtitle: {
        color: colors.muted,
        fontSize: 14,
        lineHeight: 20,
        marginTop: spacing.xs,
        textAlign: 'center',
    },
    errorBoundaryTitle: {
        color: colors.text,
        fontSize: 18,
        fontWeight: '800',
        textAlign: 'center',
    },
    errorText: {
        color: '#ffb1a3',
        fontSize: 14,
        marginTop: spacing.sm,
    },
    formatBadge: {
        height: 44,
        resizeMode: 'contain',
        width: 44,
    },
    formatBadgeMeta: {
        // Standalone "16-bit / 44.1 kHz Lossless" text line on the album
        // detail. Sits in the metaLines block so it lines up with the
        // artist/year/label entries already there.
        color: colors.accent,
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 0.4,
        marginTop: spacing.xs,
        textTransform: 'uppercase',
    },
    formatBadgeMini: {
        // Mini-player artwork is only 58x58, so the badge needs to shrink to
        // stay readable without smothering the cover art. Same top-left
        // placement as formatBadgeOverlay for visual consistency with tiles.
        height: 22,
        left: 3,
        position: 'absolute',
        top: 3,
        width: 22,
    },
    formatBadgeOverlay: {
        // Corner overlay on artwork. Top-left mirrors how Tidal and Apple
        // Music position their lossless marks — bottom corners draw the eye
        // away from the title beneath the tile.
        height: 38,
        left: 6,
        position: 'absolute',
        top: 6,
        width: 38,
    },
    formatBadgePlayer: {
        height: 36,
        marginRight: -2,
        width: 36,
    },
    formatBadgeThumb: {
        bottom: 2,
        height: 18,
        position: 'absolute',
        right: 2,
        width: 18,
    },
    fullPlayer: {
        elevation: 999,
        flex: 1,
        flexDirection: 'column',
        left: 0,
        overflow: 'hidden',
        position: 'absolute',
        right: 0,
        zIndex: 9999,
    },
    fullPlayerArtwork: {
        borderRadius: 4,
        height: '100%',
        width: '100%',
    },
    fullPlayerArtworkFallback: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.07)',
        borderColor: 'rgba(255, 255, 255, 0.12)',
        borderRadius: 4,
        borderWidth: 1,
        height: '100%',
        justifyContent: 'center',
        width: '100%',
    },
    fullPlayerArtworkLetter: {
        color: colors.accent,
        fontSize: 72,
        fontWeight: '900',
    },
    fullPlayerArtworkShadow: {
        aspectRatio: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.08)',
        borderRadius: 4,
        elevation: 12,
        flexShrink: 1,
        height: FULL_PLAYER_ARTWORK_SIZE,
        shadowColor: '#000000',
        shadowOffset: { height: 14, width: 0 },
        shadowOpacity: 0.26,
        shadowRadius: 22,
        transform: [{ translateY: 8 }],
        width: FULL_PLAYER_ARTWORK_SIZE,
    },
    fullPlayerArtworkWrap: {
        alignItems: 'center',
        flex: 1,
        justifyContent: 'center',
    },
    fullPlayerBg: {
        backgroundColor: '#000000',
        bottom: 0,
        left: 0,
        position: 'absolute',
        right: 0,
        top: 0,
    },
    fullPlayerBottom: {
        flexShrink: 0,
    },
    fullPlayerBottomLifted: {
        marginBottom: 34,
    },
    fullPlayerBottomBar: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 24,
    },
    fullPlayerBottomBarButton: {
        alignItems: 'center',
        height: 40,
        justifyContent: 'center',
        width: 40,
    },
    fullPlayerCastButton: {
        bottom: 0,
        height: 40,
        left: 0,
        opacity: 0.01,
        position: 'absolute',
        right: 0,
        top: 0,
        width: 40,
    },
    fullPlayerCastStatus: {
        color: colors.accent,
        flex: 1,
        fontSize: 12,
        fontWeight: '700',
        marginLeft: spacing.sm,
        textAlign: 'right',
    },
    fullPlayerCollapsedSurface: {
        backgroundColor: '#1c1c1e',
    },
    fullPlayerDither: {
        // Soft-light blend means the noise PNG (mean grey 128, ±18 spread)
        // perturbs the underlying gradient by ±2-3/255 per pixel without
        // shifting average brightness. That's exactly enough to dither
        // away the 8-bit quantization steps that produce visible banding
        // in long, slow gradients — and below the threshold where the
        // grain itself becomes perceivable.
        mixBlendMode: 'soft-light',
    },
    fullPlayerContent: {
        height: SCREEN_HEIGHT,
        left: 0,
        paddingBottom: FULL_PLAYER_PADDING_BOTTOM,
        paddingHorizontal: spacing.lg,
        paddingTop: FULL_PLAYER_PADDING_TOP,
        position: 'absolute',
        right: 0,
        top: 0,
    },
    fullPlayerControlSide: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 12,
        minWidth: 100,
    },
    fullPlayerControlSideRight: {
        justifyContent: 'flex-end',
    },
    fullPlayerControls: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 22,
    },
    fullPlayerDragHandle: {
        alignItems: 'center',
        paddingBottom: 6,
        paddingTop: 4,
    },
    fullPlayerDragPill: {
        backgroundColor: 'rgba(255, 255, 255, 0.32)',
        borderRadius: 999,
        height: 4,
        width: 40,
    },
    fullPlayerErrorText: {
        color: '#ffb1a3',
        fontSize: 12,
        lineHeight: 16,
        marginTop: spacing.md,
        textAlign: 'center',
    },
    fullPlayerHeader: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    fullPlayerHeaderButton: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        borderRadius: 999,
        height: 44,
        justifyContent: 'center',
        width: 44,
    },
    fullPlayerHeaderSpacer: {
        flex: 1,
    },
    fullPlayerMetadata: {
        alignItems: 'stretch',
        marginTop: spacing.lg,
        paddingHorizontal: 0,
    },
    fullPlayerProgress: {
        marginTop: 22,
    },
    fullPlayerQualityRow: {
        marginTop: spacing.sm,
    },
    fullPlayerSleepLabel: {
        color: colors.accent,
        fontSize: 12,
        fontWeight: '600',
        marginTop: spacing.xs,
        textAlign: 'center',
    },
    fullPlayerSubtitle: {
        color: 'rgba(245, 245, 245, 0.58)',
        fontSize: 18,
        fontWeight: '500',
        lineHeight: 23,
        marginTop: 4,
        textAlign: 'left',
    },
    fullPlayerTime: {
        color: 'rgba(245, 245, 245, 0.58)',
        fontSize: 13,
        fontWeight: '600',
    },
    fullPlayerTimeRight: {
        textAlign: 'right',
    },
    fullPlayerTimeRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: spacing.xs,
    },
    fullPlayerTitle: {
        color: '#ffffff',
        fontSize: 24,
        fontWeight: '900',
        letterSpacing: 0,
        lineHeight: 30,
        textAlign: 'left',
    },
    gearGlyphText: {
        fontSize: 18,
        fontWeight: '700',
        lineHeight: 22,
    },
    gestureRoot: {
        backgroundColor: colors.background,
        flex: 1,
    },
    header: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: spacing.xs,
        minHeight: 44,
    },
    homeFilterGrid: {
        columnGap: HOME_TILE_GAP,
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: spacing.sm,
        rowGap: spacing.md,
    },
    homeFilterGridArtwork: {
        aspectRatio: 1,
        backgroundColor: colors.surface,
        borderRadius: 2,
        marginBottom: spacing.xs,
        width: HOME_PRIMARY_TILE,
    },
    homeFilterGridArtworkFallback: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    homeFilterGridArtworkPodcast: {
        borderRadius: 26,
    },
    homeFilterGridTile: {
        width: HOME_PRIMARY_TILE,
    },
    homeFilterPill: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 999,
        justifyContent: 'center',
        minHeight: 34,
        paddingHorizontal: spacing.md,
    },
    homeFilterPillActive: {
        backgroundColor: colors.text,
    },
    homeFilterPills: {
        gap: spacing.xs,
        paddingBottom: spacing.sm,
        paddingTop: spacing.md,
    },
    homeFilterPillText: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '800',
    },
    homeFilterPillTextActive: {
        color: colors.background,
    },
    homeHeaderTitle: {
        color: colors.text,
        fontSize: 30,
        fontWeight: '900',
        letterSpacing: 0,
        lineHeight: 36,
    },
    homeSection: {
        marginTop: 0,
    },
    homeMultiRowColumn: {
        gap: spacing.lg,
    },
    inlineSearchBar: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 999,
        flexDirection: 'row',
        gap: spacing.sm,
        minHeight: 50,
        paddingHorizontal: spacing.md,
    },
    inlineSearchBarElevated: {
        backgroundColor: 'rgba(255,255,255,0.10)',
        borderColor: 'rgba(255,255,255,0.13)',
        borderRadius: 999,
        borderWidth: 1,
        minHeight: 52,
        paddingHorizontal: spacing.lg,
    },
    inlineSearchIconButton: {
        alignItems: 'center',
        borderRadius: 8,
        height: 34,
        justifyContent: 'center',
        width: 34,
    },
    inlineSearchInput: {
        color: colors.text,
        flex: 1,
        fontSize: 16,
        fontWeight: '700',
        minWidth: 0,
        paddingVertical: 10,
    },
    inlineSearchInputDark: {
        color: '#111111',
        fontSize: 18,
        fontWeight: '900',
    },
    inlineSearchSubmit: {
        alignItems: 'center',
        backgroundColor: colors.accent,
        borderRadius: 8,
        height: 34,
        justifyContent: 'center',
        width: 34,
    },
    input: {
        backgroundColor: colors.surface,
        borderRadius: 8,
        color: colors.text,
        fontSize: 16,
        marginTop: spacing.sm,
        paddingHorizontal: spacing.md,
        paddingVertical: 13,
    },
    inputActionButton: {
        alignItems: 'center',
        height: 44,
        justifyContent: 'center',
        width: 44,
    },
    inputWithAction: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 8,
        flexDirection: 'row',
        marginTop: spacing.sm,
        paddingRight: 4,
    },
    inputWithActionField: {
        backgroundColor: 'transparent',
        flex: 1,
        marginTop: 0,
        minWidth: 0,
        paddingRight: spacing.xs,
    },
    keyboardView: {
        flex: 1,
    },
    libraryArtworkRound: {
        borderRadius: 999,
    },
    libraryEmptyState: {
        alignItems: 'center',
        backgroundColor: colors.panel,
        borderRadius: 8,
        justifyContent: 'center',
        minHeight: 116,
        padding: spacing.lg,
    },
    libraryEyebrow: {
        color: colors.text,
        fontSize: 22,
        fontWeight: '900',
        letterSpacing: 0,
        lineHeight: 27,
    },
    libraryFilterPill: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 999,
        justifyContent: 'center',
        minHeight: 34,
        paddingHorizontal: spacing.md,
    },
    libraryFilterPillActive: {
        backgroundColor: colors.text,
    },
    libraryFilterPills: {
        gap: spacing.xs,
        paddingBottom: spacing.sm,
        paddingTop: spacing.md,
    },
    libraryFilterPillText: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '800',
    },
    libraryFilterPillTextActive: {
        color: colors.background,
    },
    libraryHeaderRow: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    libraryHeaderText: {
        flex: 1,
        minWidth: 0,
        paddingRight: spacing.md,
    },
    libraryList: {
        gap: 4,
        marginTop: spacing.md,
    },
    libraryListContent: {
        // tabBar (~62) + miniPlayer (~78) + breathing room
        paddingBottom: 200,
        paddingHorizontal: HOME_EDGE_PADDING,
        paddingTop: spacing.lg,
    },
    libraryRow: {
        alignItems: 'center',
        borderRadius: 8,
        flexDirection: 'row',
        gap: spacing.sm,
        minHeight: 62,
        padding: 6,
        position: 'relative',
    },
    libraryRowAccessory: {
        alignItems: 'center',
        height: 38,
        justifyContent: 'center',
        width: 38,
    },
    libraryRowArtwork: {
        backgroundColor: colors.surface,
        borderRadius: 7,
        height: 50,
        width: 50,
    },
    libraryRowArtworkFallback: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 7,
        height: 50,
        justifyContent: 'center',
        width: 50,
    },
    libraryRowSubtitle: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '600',
        lineHeight: 16,
    },
    libraryRowText: {
        flex: 1,
        minWidth: 0,
    },
    libraryRowDownloadIndicator: {
        bottom: 13,
        opacity: 0.82,
        position: 'absolute',
        right: 8,
    },
    libraryRowDownloadIndicatorWithAccessory: {
        right: 48,
    },
    libraryRowTitle: {
        color: colors.text,
        fontSize: 15,
        fontWeight: '800',
        lineHeight: 19,
        marginBottom: 2,
    },
    libraryScreen: {
        flex: 1,
    },
    librarySortBadge: {
        alignItems: 'center',
        backgroundColor: colors.panel,
        borderRadius: 999,
        flexDirection: 'row',
        gap: 6,
        minHeight: 32,
        paddingHorizontal: spacing.sm,
    },
    librarySortMenuHeader: {
        paddingHorizontal: 16,
        paddingTop: 16,
    },
    librarySortMenuLabelActive: {
        color: colors.accent,
    },
    librarySortText: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '800',
    },
    librarySummary: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '700',
        lineHeight: 17,
        marginTop: 2,
    },
    libraryStaticContent: {
        // Matches normal tab content padding for non-virtualized library states.
        paddingBottom: 200,
        paddingHorizontal: HOME_EDGE_PADDING,
        paddingTop: spacing.lg,
    },
    mediaArtwork: {
        aspectRatio: 1,
        backgroundColor: colors.surface,
        borderRadius: 2,
        height: HOME_PRIMARY_TILE,
        marginBottom: spacing.xs,
        width: HOME_PRIMARY_TILE,
    },
    mediaArtworkAlbum: {
        borderRadius: 2,
    },
    mediaArtworkArtist: {
        borderRadius: 999,
        height: HOME_PRIMARY_TILE - HOME_COMPACT_OFFSET,
        width: HOME_PRIMARY_TILE - HOME_COMPACT_OFFSET,
    },
    mediaArtworkBook: {
        borderRadius: 2,
        height: HOME_PRIMARY_TILE,
        width: HOME_PRIMARY_TILE,
    },
    mediaArtworkCompact: {
        borderRadius: 2,
        height: HOME_PRIMARY_TILE,
        width: HOME_PRIMARY_TILE,
    },
    mediaArtworkFallback: {
        alignItems: 'center',
        aspectRatio: 1,
        backgroundColor: colors.surface,
        borderRadius: 2,
        height: HOME_PRIMARY_TILE,
        justifyContent: 'center',
        marginBottom: spacing.xs,
        width: HOME_PRIMARY_TILE,
    },
    mediaArtworkGrid: {
        borderRadius: 30,
        height: HOME_PRIMARY_TILE - HOME_ROUNDED_OFFSET,
        width: HOME_PRIMARY_TILE - HOME_ROUNDED_OFFSET,
    },
    mediaArtworkLetter: {
        color: colors.accent,
        fontSize: 48,
        fontWeight: '900',
    },
    mediaArtworkPlaylist: {
        borderRadius: 2,
        height: HOME_PRIMARY_TILE,
        width: HOME_PRIMARY_TILE,
    },
    mediaArtworkPodcast: {
        borderRadius: 26,
        height: HOME_PRIMARY_TILE - HOME_ROUNDED_OFFSET,
        width: HOME_PRIMARY_TILE - HOME_ROUNDED_OFFSET,
    },
    mediaArtworkRadio: {
        backgroundColor: 'transparent',
        borderRadius: 32,
    },
    mediaArtworkWide: {
        borderRadius: 2,
        height: 112,
        marginBottom: 0,
        width: 112,
    },
    mediaContextActionDestructive: {
        color: '#ff7a6e',
    },
    mediaContextActionIcon: {
        alignItems: 'center',
        height: 22,
        justifyContent: 'center',
        marginRight: 14,
        width: 22,
    },
    mediaContextActionLabel: {
        color: colors.text,
        flex: 1,
        fontSize: 15,
        fontWeight: '600',
        letterSpacing: 0.1,
        lineHeight: 18,
    },
    mediaContextActionRow: {
        alignItems: 'center',
        borderBottomColor: 'rgba(255, 255, 255, 0.045)',
        borderBottomWidth: 1,
        flexDirection: 'row',
        height: 50,
        paddingHorizontal: 16,
    },
    mediaContextActionRowLast: {
        borderBottomWidth: 0,
    },
    mediaContextActions: {
        marginTop: 4,
        paddingBottom: 4,
    },
    mediaContextArtwork: {
        backgroundColor: '#2a2a2c',
        borderRadius: 6,
        height: 44,
        width: 44,
    },
    mediaContextArtworkFallback: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    mediaContextArtworkRound: {
        borderRadius: 22,
    },
    mediaContextBackdrop: {
        backgroundColor: 'rgba(0, 0, 0, 0.62)',
        bottom: 0,
        flex: 1,
        justifyContent: 'flex-end',
        left: 0,
        position: 'absolute',
        right: 0,
        top: 0,
    },
    mediaContextBackdropPress: {
        bottom: 0,
        left: 0,
        position: 'absolute',
        right: 0,
        top: 0,
    },
    mediaContextDivider: {
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        height: 1,
        marginTop: 12,
    },
    mediaContextEmpty: {
        color: colors.muted,
        fontSize: 13,
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    mediaContextEyebrow: {
        color: colors.accent,
        fontSize: 10,
        fontWeight: '800',
        letterSpacing: 1.2,
        marginBottom: 2,
        textTransform: 'uppercase',
    },
    mediaContextFeedback: {
        color: colors.accent,
        fontSize: 12,
        fontWeight: '700',
        paddingBottom: 14,
        paddingHorizontal: 16,
    },
    mediaContextHeaderRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 12,
        paddingHorizontal: 14,
        paddingTop: 14,
    },
    mediaContextHeaderText: {
        flex: 1,
    },
    mediaContextSheet: {
        backgroundColor: 'rgba(22, 22, 24, 0.985)',
        borderColor: 'rgba(255, 255, 255, 0.07)',
        borderRadius: 18,
        borderWidth: 0.5,
        elevation: 18,
        marginBottom: 28,
        marginHorizontal: 12,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { height: 12, width: 0 },
        shadowOpacity: 0.45,
        shadowRadius: 24,
    },
    mediaContextSubtitle: {
        color: colors.muted,
        fontSize: 13,
        fontWeight: '500',
        lineHeight: 16,
    },
    mediaContextTitle: {
        color: colors.text,
        fontSize: 17,
        fontWeight: '800',
        letterSpacing: 0.1,
        lineHeight: 21,
    },
    mediaSubtitle: {
        color: colors.muted,
        fontSize: 12,
        lineHeight: 16,
    },
    mediaSubtitleCentered: {
        textAlign: 'center',
    },
    mediaSubtitleInline: {
        flexShrink: 1,
        minWidth: 0,
    },
    mediaInfoRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 4,
        minHeight: 16,
        minWidth: 0,
    },
    mediaInfoRowCentered: {
        justifyContent: 'center',
    },
    mediaText: {
        minWidth: 0,
        position: 'relative',
    },
    mediaTextCentered: {
        alignItems: 'center',
    },
    mediaTextWide: {
        flex: 1,
        justifyContent: 'center',
        minWidth: 0,
    },
    mediaTile: {
        marginRight: HOME_TILE_GAP,
        position: 'relative',
        width: HOME_PRIMARY_TILE,
    },
    mediaTileAlbum: {
        width: HOME_PRIMARY_TILE,
    },
    mediaTileArtist: {
        alignItems: 'center',
        width: HOME_PRIMARY_TILE - HOME_COMPACT_OFFSET,
    },
    mediaTileBook: {
        width: HOME_PRIMARY_TILE,
    },
    mediaTileCompact: {
        height: HOME_PRIMARY_TILE + 58,
        width: HOME_PRIMARY_TILE,
    },
    mediaTileContinue: {
        borderColor: 'rgba(255, 255, 255, 0.06)',
        borderWidth: 1,
        width: 320,
    },
    mediaTileGrid: {
        alignItems: 'center',
        width: HOME_PRIMARY_TILE - HOME_ROUNDED_OFFSET,
    },
    mediaTilePlaylist: {
        width: HOME_PRIMARY_TILE,
    },
    mediaTilePodcast: {
        width: HOME_PRIMARY_TILE - HOME_ROUNDED_OFFSET,
    },
    mediaTileWide: {
        backgroundColor: colors.panel,
        borderRadius: 4,
        flexDirection: 'row',
        gap: spacing.md,
        minHeight: 136,
        padding: 12,
        width: 320,
    },
    mediaTitle: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '800',
        lineHeight: 18,
        marginBottom: 2,
    },
    mediaTitleCentered: {
        textAlign: 'center',
    },
    mediaDownloadIndicator: {
        opacity: 0.82,
        paddingTop: 1,
    },
    mediaTitleWide: {
        fontSize: 15,
        lineHeight: 19,
    },
    miniPlayer: {
        backgroundColor: '#1c1c1e',
        borderTopLeftRadius: MINI_PLAYER_RADIUS,
        borderTopRightRadius: MINI_PLAYER_RADIUS,
        bottom: MINI_PLAYER_BOTTOM,
        left: 0,
        overflow: 'hidden',
        position: 'absolute',
        right: 0,
        // zIndex puts the MiniPlayer hit area above the ScrollView on every
        // page (the issue on artist/album/playlist detail). No elevation —
        // that draws an Android drop shadow which broke the visual seam with
        // the tab bar.
        zIndex: 10000,
    },
    miniPlayerArtwork: {
        borderRadius: 10,
        height: MINI_PLAYER_ARTWORK_SIZE,
        width: MINI_PLAYER_ARTWORK_SIZE,
    },
    miniPlayerArtworkContainer: {
        height: MINI_PLAYER_ARTWORK_SIZE,
        position: 'relative',
        width: MINI_PLAYER_ARTWORK_SIZE,
    },
    miniPlayerArtworkFallback: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 10,
        height: MINI_PLAYER_ARTWORK_SIZE,
        justifyContent: 'center',
        width: MINI_PLAYER_ARTWORK_SIZE,
    },
    miniPlayerArtworkLetter: {
        color: colors.text,
        fontSize: 23,
        fontWeight: '800',
    },
    miniPlayerPlayButton: {
        alignItems: 'center',
        height: 50,
        justifyContent: 'center',
        width: 50,
    },
    miniPlayerSubtitle: {
        color: colors.muted,
        fontSize: 14,
        lineHeight: 18,
    },
    miniPlayerText: {
        flex: 1,
    },
    miniPlayerTitle: {
        color: colors.text,
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 2,
    },
    miniPlayerTitleRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 7,
        minWidth: 0,
    },
    miniPlayerTouchable: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 13,
        paddingHorizontal: 18,
        paddingVertical: MINI_PLAYER_VERTICAL_PADDING,
    },
    modalBackdrop: {
        backgroundColor: 'rgba(0,0,0,0.55)',
        flex: 1,
        justifyContent: 'flex-end',
    },
    moreGlyph: {
        alignItems: 'center',
        height: 24,
        justifyContent: 'center',
        width: 24,
    },
    moreGlyphDot: {
        borderRadius: 999,
        height: 3.2,
        marginVertical: 1.5,
        width: 3.2,
    },
    mutedText: {
        color: colors.muted,
        fontSize: 14,
        lineHeight: 20,
    },
    pauseGlyph: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 4,
        justifyContent: 'center',
    },
    pauseGlyphBar: {
        borderRadius: 2,
        height: '100%',
        width: 5,
    },
    playCircleGlyph: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        borderRadius: 999,
        height: 32,
        justifyContent: 'center',
        width: 32,
    },
    playerControlButton: {
        alignItems: 'center',
        borderRadius: 999,
        height: 44,
        justifyContent: 'center',
        width: 44,
    },
    playerControlButtonPrimary: {
        height: 68,
        width: 68,
    },
    playerControlButtonSpacer: {
        height: 44,
        width: 44,
    },
    playGlyph: {
        borderBottomColor: 'transparent',
        borderTopColor: 'transparent',
        height: 0,
        marginLeft: 2,
        width: 0,
    },
    playlistControlDirectionPill: {
        // The arrow pill stands a bit apart — it's a TOGGLE, not a member of
        // the sort-axis exclusive group.
        marginLeft: spacing.sm,
        minWidth: 36,
    },
    playlistControlGroup: {
        alignItems: 'center',
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.sm,
    },
    playlistControlLabel: {
        color: colors.muted,
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 0.6,
        textTransform: 'uppercase',
    },
    playlistControlPill: {
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderColor: 'rgba(255, 255, 255, 0.12)',
        borderRadius: 999,
        borderWidth: 1,
        paddingHorizontal: spacing.sm,
        paddingVertical: 6,
    },
    playlistControlPillActive: {
        backgroundColor: colors.accent,
        borderColor: colors.accent,
    },
    playlistControlPillRow: {
        alignItems: 'center',
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 6,
    },
    playlistControlPillText: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '700',
    },
    playlistControlPillTextActive: {
        color: '#050505',
    },
    playlistControlsBlock: {
        // Two stacked label+pill rows above the playlist track list. Block
        // (not row) so even on narrow phones the sort axis never wraps under
        // an active filter pill and lose its breathing room.
        gap: spacing.sm,
        marginBottom: spacing.sm,
        marginTop: spacing.xs,
    },
    playlistListEmpty: {
        color: colors.muted,
        fontSize: 14,
        lineHeight: 20,
        paddingVertical: spacing.md,
    },
    playlistSearchAnimatedWrapper: {
        overflow: 'hidden',
    },
    playlistHeroSearchBar: {
        marginTop: spacing.xs,
    },
    playlistHeroSearchWrapper: {
        alignSelf: 'stretch',
        width: '100%',
    },
    playlistSearchBar: {
        marginBottom: spacing.sm,
        marginTop: spacing.xs,
    },
    playlistHeaderActions: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
    },
    playlistPillButton: {
        alignItems: 'center',
        backgroundColor: colors.accent,
        borderRadius: 999,
        flexDirection: 'row',
        gap: 8,
        height: 40,
        justifyContent: 'center',
        paddingHorizontal: 18,
    },
    playlistPillButtonText: {
        color: colors.background,
        fontSize: 14,
        fontWeight: '900',
    },
    playlistScreen: {
        marginTop: spacing.sm,
    },
    playlistStackIcon: {
        height: 52,
        position: 'relative',
        width: 52,
    },
    playlistStackLayer: {
        backgroundColor: colors.accentSoft,
        borderRadius: 8,
        height: 42,
        left: 2,
        position: 'absolute',
        top: 8,
        width: 42,
    },
    playlistStackLayerOffset: {
        backgroundColor: colors.surface,
        left: 8,
        top: 2,
    },
    playlistSummary: {
        color: colors.muted,
        fontSize: 14,
        fontWeight: '700',
        lineHeight: 20,
        marginTop: 2,
    },
    playlistTopPanel: {
        alignItems: 'center',
        backgroundColor: colors.panel,
        borderRadius: 8,
        flexDirection: 'row',
        justifyContent: 'space-between',
        minHeight: 86,
        padding: spacing.md,
    },
    primaryButton: {
        alignItems: 'center',
        backgroundColor: colors.accent,
        borderRadius: 8,
        height: 48,
        justifyContent: 'center',
        marginTop: spacing.md,
    },
    primaryButtonText: {
        color: '#050505',
        fontSize: 16,
        fontWeight: '800',
    },
    qualityBadge: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderColor: 'rgba(255, 255, 255, 0.16)',
        borderRadius: 6,
        borderWidth: 1,
        flexShrink: 1,
        maxWidth: 150,
        minWidth: 0,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    qualityBadgeDirect: {
        backgroundColor: 'rgba(202, 160, 79, 0.24)',
        borderColor: 'rgba(202, 160, 79, 0.58)',
    },
    qualityBadgeRow: {
        flexDirection: 'row',
        flexWrap: 'nowrap',
        gap: 6,
        justifyContent: 'center',
        marginTop: spacing.md,
        width: '100%',
    },
    qualityBadgeText: {
        color: colors.text,
        flexShrink: 1,
        fontSize: 11,
        fontWeight: '900',
        lineHeight: 14,
    },
    qualityBadgeTextDirect: {
        color: colors.accent,
    },
    qualityBadgeTextTranscoded: {
        color: '#e0a06d',
    },
    qualityBadgeTextUnknown: {
        color: colors.muted,
    },
    qualityBadgeTranscoded: {
        backgroundColor: 'rgba(220, 110, 40, 0.18)',
        borderColor: 'rgba(220, 110, 40, 0.34)',
    },
    qualityBadgeUnknown: {
        backgroundColor: 'rgba(255, 255, 255, 0.07)',
        borderColor: 'rgba(255, 255, 255, 0.14)',
    },
    queueChapterNumber: {
        alignItems: 'center',
        height: 44,
        justifyContent: 'center',
        width: 44,
    },
    queueChapterNumberText: {
        color: colors.muted,
        fontSize: 14,
        fontWeight: '700',
    },
    queueNowPlayingIndicator: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 2,
        height: 18,
        width: 18,
    },
    queueRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 12,
        paddingHorizontal: spacing.lg,
        paddingVertical: 8,
    },
    queueRowBody: {
        flex: 1,
        minWidth: 0,
    },
    queueRowPlayingBar: {
        backgroundColor: colors.accent,
        borderRadius: 1.5,
        height: 14,
        width: 3,
    },
    queueRowPlayingBarShort: {
        height: 9,
    },
    queueRowSubtitle: {
        color: colors.muted,
        fontSize: 13,
        marginTop: 2,
    },
    queueRowThumb: {
        backgroundColor: 'rgba(255,255,255,0.06)',
        borderRadius: 6,
        height: 44,
        width: 44,
    },
    queueRowThumbFallback: {
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.06)',
        borderRadius: 6,
        height: 44,
        justifyContent: 'center',
        width: 44,
    },
    queueRowThumbLetter: {
        color: colors.muted,
        fontSize: 18,
        fontWeight: '700',
    },
    queueRowTitle: {
        color: colors.text,
        fontSize: 15,
        fontWeight: '600',
    },
    queueSheet: {
        backgroundColor: 'rgba(12, 10, 8, 0.96)',
        borderTopLeftRadius: 18,
        borderTopRightRadius: 18,
        bottom: 0,
        elevation: 1001,
        height: QUEUE_SHEET_HEIGHT,
        left: 0,
        position: 'absolute',
        right: 0,
        zIndex: 10001,
    },
    queueSheetBackdrop: {
        backgroundColor: '#000000',
        bottom: 0,
        elevation: 1000,
        left: 0,
        position: 'absolute',
        right: 0,
        top: 0,
        zIndex: 10000,
    },
    queueSheetCloseButton: {
        alignItems: 'center',
        borderRadius: 999,
        height: 42,
        justifyContent: 'center',
        width: 42,
    },
    queueSheetContent: {
        paddingBottom: spacing.xl,
    },
    queueSheetEmpty: {
        color: colors.muted,
        paddingHorizontal: spacing.lg,
        paddingTop: spacing.md,
    },
    queueSheetHandle: {
        alignSelf: 'center',
        backgroundColor: 'rgba(255,255,255,0.24)',
        borderRadius: 999,
        height: 4,
        marginBottom: 10,
        marginTop: 10,
        width: 38,
    },
    queueSheetHeader: {
        paddingTop: 2,
    },
    queueSheetScroll: {
        flex: 1,
    },
    queueSheetTitle: {
        color: colors.text,
        flex: 1,
        fontSize: 18,
        fontWeight: '800',
    },
    queueSheetTitleRow: {
        alignItems: 'center',
        flexDirection: 'row',
        paddingBottom: spacing.sm,
        paddingLeft: spacing.lg,
        paddingRight: spacing.sm,
    },
    radioCard: {
        alignItems: 'center',
        backgroundColor: 'transparent',
        borderRadius: 8,
        marginBottom: spacing.sm,
        paddingHorizontal: spacing.xs,
        paddingVertical: spacing.sm,
        width: '48.5%',
    },
    radioCardArtwork: {
        aspectRatio: 1,
        borderRadius: 18,
        marginBottom: spacing.sm,
        width: '100%',
    },
    radioCardArtworkFallback: {
        alignItems: 'center',
        aspectRatio: 1,
        backgroundColor: 'rgba(232, 213, 176, 0.12)',
        borderRadius: 18,
        justifyContent: 'center',
        marginBottom: spacing.sm,
        width: '100%',
    },
    radioCardNowPlaying: {
        color: colors.accent,
        fontSize: 11,
        fontWeight: '800',
        marginTop: 2,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    radioCardTitle: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '900',
        lineHeight: 18,
        marginBottom: 2,
        textAlign: 'center',
    },
    radioGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginTop: spacing.sm,
    },
    radioGridHeader: {
        alignItems: 'flex-end',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: spacing.xl,
    },
    radioGridHeaderCompact: {
        marginTop: 0,
    },
    radioHeaderActions: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.xs,
    },
    radioAddIconButton: {
        alignItems: 'center',
        borderRadius: 999,
        height: 32,
        justifyContent: 'center',
        width: 32,
    },
    radioEmptyText: {
        marginTop: spacing.md,
    },
    radioHero: {
        alignItems: 'center',
        backgroundColor: colors.panel,
        borderRadius: 8,
        flexDirection: 'row',
        gap: spacing.md,
        minHeight: 154,
        padding: spacing.md,
    },
    radioHeroArtwork: {
        borderRadius: 22,
        height: 106,
        width: 106,
    },
    radioHeroArtworkFallback: {
        alignItems: 'center',
        backgroundColor: 'rgba(232, 213, 176, 0.12)',
        borderRadius: 22,
        height: 106,
        justifyContent: 'center',
        width: 106,
    },
    radioHeroArtworkWrap: {
        flexShrink: 0,
    },
    radioHeroEyebrow: {
        color: colors.accent,
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 0.5,
        marginBottom: 4,
        textTransform: 'uppercase',
    },
    radioHeroPlay: {
        alignItems: 'center',
        alignSelf: 'flex-end',
        backgroundColor: colors.accent,
        borderRadius: 999,
        height: 48,
        justifyContent: 'center',
        width: 48,
    },
    radioHeroSubtitle: {
        color: colors.muted,
        fontSize: 13,
        fontWeight: '700',
        lineHeight: 18,
        marginTop: 4,
    },
    radioHeroText: {
        flex: 1,
        minWidth: 0,
    },
    radioHeroTitle: {
        color: colors.text,
        fontSize: 23,
        fontWeight: '900',
        lineHeight: 28,
    },
    radioScreen: {
        marginTop: spacing.sm,
    },
    radioSortButton: {
        alignItems: 'center',
        borderRadius: 999,
        justifyContent: 'center',
        minHeight: 32,
        paddingHorizontal: 4,
    },
    radioSortText: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '700',
        lineHeight: 17,
    },
    relatedArtistArtwork: {
        backgroundColor: colors.surface,
        borderRadius: 999,
        height: 112,
        marginBottom: spacing.xs,
        width: 112,
    },
    relatedArtistArtworkFallback: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    relatedArtistTile: {
        alignItems: 'center',
        marginRight: spacing.md,
        width: 112,
    },
    relatedArtistTitle: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '700',
        textAlign: 'center',
    },
    root: {
        backgroundColor: colors.background,
        flex: 1,
    },
    row: {
        borderColor: colors.border,
        borderTopWidth: 1,
        paddingVertical: spacing.md,
    },
    rowTitle: {
        color: colors.text,
        fontSize: 17,
        fontWeight: '700',
        marginBottom: 4,
    },
    safeArea: {
        backgroundColor: colors.background,
        flex: 1,
        paddingTop: Platform.OS === 'android' ? 24 : 0,
    },
    searchArtwork: {
        backgroundColor: colors.surface,
        borderRadius: 8,
        height: 52,
        width: 52,
    },
    searchArtworkFallback: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 8,
        height: 52,
        justifyContent: 'center',
        width: 52,
    },
    searchArtworkLetter: {
        color: colors.accent,
        fontSize: 20,
        fontWeight: '900',
    },
    searchArtworkRound: {
        borderRadius: 26,
    },
    searchBrowseSection: {
        marginTop: spacing.xl,
    },
    searchBrowseTitle: {
        color: colors.text,
        fontSize: 24,
        fontWeight: '900',
        lineHeight: 30,
        marginBottom: spacing.md,
    },
    searchGlyph: {
        height: 22,
        position: 'relative',
        width: 22,
    },
    searchGlyphCircle: {
        borderRadius: 7,
        borderWidth: 2,
        height: 14,
        left: 2,
        position: 'absolute',
        top: 2,
        width: 14,
    },
    searchGlyphHandle: {
        borderRadius: 999,
        bottom: 3,
        height: 2,
        position: 'absolute',
        right: 2,
        transform: [{ rotate: '45deg' }],
        width: 8,
    },
    searchOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.72)',
        zIndex: 11000,
    },
    searchOverlayBar: {
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.10)',
        borderColor: 'rgba(255,255,255,0.13)',
        borderRadius: 999,
        borderWidth: 1,
        flexDirection: 'row',
        gap: spacing.sm,
        minHeight: 52,
        paddingHorizontal: spacing.lg,
    },
    searchOverlayClear: {
        alignItems: 'center',
        height: 34,
        justifyContent: 'center',
        width: 34,
    },
    searchOverlayInput: {
        color: colors.text,
        flex: 1,
        fontSize: 16,
        fontWeight: '700',
        paddingVertical: 10,
    },
    searchOverlayPanel: {
        backgroundColor: colors.background,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        bottom: 0,
        left: 0,
        paddingBottom: 30,
        paddingHorizontal: spacing.lg,
        paddingTop: spacing.lg,
        position: 'absolute',
        right: 0,
        top: 80,
    },
    searchOverlayResults: {
        marginTop: spacing.md,
    },
    searchPanel: {
        marginTop: spacing.lg,
    },
    searchRecentSection: {
        marginTop: spacing.xl,
    },
    searchResultSection: {
        marginTop: spacing.xl,
    },
    searchRow: {
        alignItems: 'center',
        borderColor: colors.border,
        borderTopWidth: 1,
        flexDirection: 'row',
        gap: spacing.sm,
        paddingVertical: spacing.sm,
    },
    searchRowText: {
        flex: 1,
    },
    searchScopePill: {
        alignItems: 'center',
        backgroundColor: colors.panel,
        borderColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: 999,
        borderWidth: 1,
        justifyContent: 'center',
        minHeight: 34,
        paddingHorizontal: spacing.md,
    },
    searchScopePillActive: {
        backgroundColor: colors.text,
        borderColor: colors.text,
    },
    searchScopePills: {
        gap: spacing.xs,
        paddingTop: spacing.md,
    },
    searchScopePillText: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '800',
    },
    searchScopePillTextActive: {
        color: colors.background,
    },
    searchSourceAccent: {
        borderRadius: 999,
        height: 5,
        marginBottom: spacing.sm,
        width: 34,
    },
    searchSourceCard: {
        backgroundColor: colors.panel,
        borderColor: 'rgba(255, 255, 255, 0.06)',
        borderRadius: 8,
        borderWidth: 1,
        marginRight: spacing.sm,
        minHeight: 104,
        padding: spacing.md,
        width: 164,
    },
    searchSourceSubtitle: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '700',
        lineHeight: 16,
        marginTop: 3,
    },
    searchSourceTitle: {
        color: colors.text,
        fontSize: 16,
        fontWeight: '900',
        lineHeight: 20,
    },
    searchSurfaceSubtitle: {
        color: colors.muted,
        fontSize: 14,
        fontWeight: '600',
        lineHeight: 20,
        marginTop: 4,
    },
    searchSurfaceTitle: {
        color: colors.text,
        fontSize: 22,
        fontWeight: '900',
        lineHeight: 28,
    },
    searchTitle: {
        color: colors.text,
        fontSize: 15,
        fontWeight: '800',
        marginBottom: 2,
    },
    secondaryButton: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 8,
        height: 40,
        justifyContent: 'center',
        marginTop: spacing.md,
    },
    secondaryButtonText: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '800',
    },
    section: {
        backgroundColor: colors.panel,
        borderRadius: 8,
        marginTop: spacing.lg,
        padding: spacing.md,
    },
    sectionHeaderRow: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingRight: spacing.sm,
    },
    sectionTitle: {
        color: colors.text,
        fontSize: 22,
        fontWeight: '900',
        letterSpacing: 0,
        marginBottom: 4,
        marginTop: 4,
    },
    sectionViewAll: {
        paddingHorizontal: spacing.xs,
        paddingVertical: 4,
    },
    sectionViewAllLabel: {
        color: colors.accent,
        fontSize: 13,
        fontWeight: '700',
    },
    seekSegment: {
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        borderRadius: 999,
        flexBasis: 0,
        height: 6,
        overflow: 'hidden',
    },
    seekSegmentFill: {
        borderRadius: 999,
        height: '100%',
    },
    seekSegmentLive: {
        flex: 1,
    },
    seekSegmentLiveFill: {
        height: '100%',
        opacity: 0.95,
        width: '100%',
    },
    seekThumb: {
        borderRadius: 999,
        bottom: -3,
        position: 'absolute',
        top: -3,
        width: 5,
    },
    segment: {
        alignItems: 'center',
        borderRadius: 7,
        flex: 1,
        justifyContent: 'center',
        minHeight: 38,
        paddingHorizontal: spacing.xs,
    },
    segmentActive: {
        backgroundColor: colors.accentSoft,
    },
    segmentedControl: {
        backgroundColor: colors.background,
        borderRadius: 8,
        flexDirection: 'row',
        gap: 4,
        padding: 4,
    },
    segmentedSeekTrack: {
        alignItems: 'stretch',
        flexDirection: 'row',
        height: 14,
        paddingVertical: 4,
    },
    segmentLabel: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '700',
        textTransform: 'capitalize',
    },
    segmentLabelActive: {
        color: colors.accent,
    },
    settingsRoot: {
        // No panel background — settings rows sit directly on the app black
        // so they read as separate "blobs" rather than as one slab.
        marginTop: spacing.lg,
    },
    settingsRootTitle: {
        color: colors.text,
        fontSize: 22,
        fontWeight: '900',
        marginBottom: spacing.md,
    },
    settingsRow: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 14,
        flexDirection: 'row',
        gap: spacing.md,
        marginTop: spacing.sm,
        paddingHorizontal: spacing.md,
        paddingVertical: 14,
    },
    settingsRowSubtitle: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '600',
    },
    settingsRowText: {
        flex: 1,
    },
    settingsRowTitle: {
        color: colors.text,
        fontSize: 15,
        fontWeight: '800',
        marginBottom: 2,
    },
    shuffleGlyph: {
        height: 18,
        position: 'relative',
        width: 20,
    },
    shuffleGlyphArrow: {
        borderLeftColor: 'transparent',
        borderLeftWidth: 4,
        borderRightColor: 'transparent',
        borderRightWidth: 4,
        borderTopWidth: 5,
        height: 0,
        position: 'absolute',
        right: 0,
        width: 0,
    },
    shuffleGlyphLine: {
        borderRadius: 999,
        height: 2,
        left: 0,
        position: 'absolute',
        top: 4,
        width: 14,
    },
    skipGlyph: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
    },
    skipGlyphBar: {
        borderRadius: 2,
        height: 17,
        width: 3,
    },
    skipGlyphTriangle: {
        borderBottomColor: 'transparent',
        borderTopColor: 'transparent',
        height: 0,
        width: 0,
    },
    skipGlyphTriangles: {
        flexDirection: 'row',
        gap: 1,
    },
    sleepPill: {
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.06)',
        borderRadius: 999,
        flexBasis: '30%',
        flexGrow: 1,
        justifyContent: 'center',
        paddingHorizontal: 12,
        paddingVertical: 14,
    },
    sleepPillActive: {
        backgroundColor: 'rgba(232, 213, 176, 0.18)',
        borderColor: colors.accent,
        borderWidth: 1,
    },
    sleepPillGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        paddingBottom: 12,
        paddingHorizontal: spacing.lg,
        paddingTop: 4,
    },
    sleepPillText: {
        color: colors.text,
        fontSize: 15,
        fontWeight: '600',
    },
    sleepPillTextActive: {
        color: colors.accent,
    },
    sleepPillWide: {
        flexBasis: '100%',
    },
    sortGlyph: {
        alignItems: 'flex-start',
        gap: 3,
        width: 15,
    },
    sortGlyphLine: {
        borderRadius: 999,
        height: 2,
    },
    starGlyph: {
        alignItems: 'center',
        height: 24,
        justifyContent: 'center',
        width: 24,
    },
    starGlyphText: {
        fontSize: 18,
        lineHeight: 22,
    },
    statusPanel: {
        backgroundColor: colors.surface,
        borderRadius: 8,
        padding: spacing.md,
    },
    statusTitle: {
        color: colors.text,
        fontSize: 16,
        fontWeight: '800',
        marginBottom: 4,
    },
    stepGlyphText: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '900',
    },
    streamInfoLabel: {
        color: colors.accent,
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 0.4,
        marginBottom: 2,
        textTransform: 'uppercase',
    },
    streamInfoRow: {
        paddingVertical: spacing.xs,
    },
    streamInfoValue: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '600',
        lineHeight: 18,
    },
    tabBar: {
        backgroundColor: '#1c1c1e',
        bottom: 0,
        flexDirection: 'row',
        left: 0,
        paddingBottom: 12,
        paddingHorizontal: spacing.xs,
        paddingTop: 8,
        position: 'absolute',
        right: 0,
    },
    tabScene: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: colors.background,
    },
    tabSceneActive: {
        opacity: 1,
        zIndex: 1,
    },
    tabSceneHidden: {
        opacity: 0,
        zIndex: 0,
    },
    tabSceneHost: {
        flex: 1,
        overflow: 'hidden',
        position: 'relative',
    },
    tabUtilityScene: {
        flex: 1,
    },
    tabButton: {
        alignItems: 'center',
        borderRadius: 8,
        flex: 1,
        justifyContent: 'center',
        minHeight: 56,
        paddingHorizontal: 2,
    },
    tabButtonActive: {},
    tabHomeBody: {
        borderRadius: 2,
        borderWidth: 2,
        bottom: 2,
        height: 11,
        position: 'absolute',
        width: 15,
    },
    tabHomeRoofLeft: {
        borderRadius: 999,
        height: 2,
        left: 5,
        position: 'absolute',
        top: 6,
        transform: [{ rotate: '-42deg' }],
        width: 11,
    },
    tabHomeRoofRight: {
        borderRadius: 999,
        height: 2,
        position: 'absolute',
        right: 5,
        top: 6,
        transform: [{ rotate: '42deg' }],
        width: 11,
    },
    tabIcon: {
        alignItems: 'center',
        flexDirection: 'row',
        height: 24,
        justifyContent: 'center',
        position: 'relative',
        width: 24,
    },
    tabLabel: {
        color: colors.muted,
        fontSize: 10,
        fontWeight: '800',
        marginTop: 4,
    },
    tabLabelActive: {
        color: colors.text,
    },
    tabLibraryBook: {
        borderRadius: 2,
        borderWidth: 1.8,
        height: 18,
        marginHorizontal: 1,
        width: 5,
    },
    tabPlaylistLine: {
        borderRadius: 999,
        height: 2.2,
        left: 3,
        position: 'absolute',
        width: 18,
    },
    tabPlaylistPlay: {
        borderBottomColor: 'transparent',
        borderBottomWidth: 4,
        borderLeftWidth: 7,
        borderTopColor: 'transparent',
        borderTopWidth: 4,
        height: 0,
        position: 'absolute',
        right: 1,
        top: 8,
        width: 0,
    },
    tabRadioAntenna: {
        borderRadius: 999,
        height: 8,
        position: 'absolute',
        right: 6,
        top: 2,
        transform: [{ rotate: '34deg' }],
        width: 2,
    },
    tabRadioBody: {
        borderRadius: 4,
        borderWidth: 1.8,
        bottom: 3,
        height: 13,
        position: 'absolute',
        width: 19,
    },
    tabRadioDot: {
        borderRadius: 3,
        bottom: 7,
        height: 6,
        left: 5,
        position: 'absolute',
        width: 6,
    },
    tabRadioLine: {
        borderRadius: 999,
        bottom: 8,
        height: 2,
        position: 'absolute',
        right: 5,
        width: 6,
    },
    tabSearchCircle: {
        borderRadius: 8,
        borderWidth: 2,
        height: 15,
        left: 3,
        position: 'absolute',
        top: 3,
        width: 15,
    },
    tabSearchHandle: {
        borderRadius: 999,
        bottom: 3,
        height: 2.2,
        position: 'absolute',
        right: 3,
        transform: [{ rotate: '45deg' }],
        width: 8,
    },
    title: {
        color: colors.text,
        fontSize: 34,
        fontWeight: '900',
        letterSpacing: 0,
    },
    trackArtwork: {
        borderRadius: 6,
        height: 44,
        width: 44,
    },
    trackArtworkFallback: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 6,
        height: 44,
        justifyContent: 'center',
        width: 44,
    },
    trackArtworkLetter: {
        color: colors.muted,
        fontSize: 16,
        fontWeight: '700',
    },
    trackMetadataLine: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 6,
        minWidth: 0,
    },
    trackMetadataText: {
        flexShrink: 1,
        minWidth: 0,
    },
    trackMenuButton: {
        alignItems: 'center',
        borderRadius: 999,
        height: 38,
        justifyContent: 'center',
        opacity: 0.68,
        width: 38,
    },
    trackRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
        minHeight: 62,
        paddingVertical: 9,
    },
    trackText: {
        flex: 1,
        justifyContent: 'center',
        minWidth: 0,
    },
    trackTitle: {
        color: colors.text,
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: 0,
        lineHeight: 21,
        marginBottom: 2,
    },
    viewAllBackArrow: {
        color: colors.text,
        fontSize: 28,
        fontWeight: '300',
        lineHeight: 28,
    },
    viewAllBackButton: {
        alignItems: 'center',
        height: 36,
        justifyContent: 'center',
        width: 36,
    },
    viewAllBody: {
        flex: 1,
        position: 'relative',
    },
    viewAllRow: {
        flexDirection: 'row',
        gap: HOME_TILE_GAP,
        paddingHorizontal: HOME_EDGE_PADDING,
    },
    viewAllTilePlaceholder: {
        height: VIEW_ALL_TILE_HEIGHT,
        width: VIEW_ALL_TILE_SIZE,
    },
    viewAllEmpty: {
        color: colors.muted,
        padding: spacing.lg,
    },
    viewAllHeader: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: spacing.sm,
        paddingVertical: spacing.sm,
    },
    viewAllJumpOverlay: {
        alignItems: 'center',
        alignSelf: 'center',
        backgroundColor: 'rgba(24, 24, 24, 0.88)',
        borderColor: 'rgba(255, 255, 255, 0.12)',
        borderRadius: 24,
        borderWidth: StyleSheet.hairlineWidth,
        height: 96,
        justifyContent: 'center',
        position: 'absolute',
        top: '36%',
        width: 96,
    },
    viewAllJumpOverlayText: {
        color: colors.text,
        fontSize: 48,
        fontWeight: '900',
        includeFontPadding: false,
        lineHeight: 56,
        textAlign: 'center',
    },
    viewAllListContent: {
        gap: HOME_TILE_GAP,
        paddingBottom: MINI_PLAYER_BOTTOM + MINI_PLAYER_HEIGHT + spacing.xl,
        // Leave room on the right edge so tiles don't sit under the sidebar.
        paddingRight: VIEW_ALL_SIDEBAR_GUTTER,
    },
    viewAllScreen: {
        flex: 1,
    },
    viewAllTile: {
        height: VIEW_ALL_TILE_HEIGHT,
        position: 'relative',
        width: VIEW_ALL_TILE_SIZE,
    },
    viewAllTileArtwork: {
        aspectRatio: 1,
        borderRadius: 2,
        marginBottom: 6,
        width: '100%',
    },
    viewAllTileArtworkFallback: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        justifyContent: 'center',
    },
    viewAllTileSubtitle: {
        color: colors.muted,
        fontSize: 12,
        lineHeight: 16,
        paddingHorizontal: 2,
    },
    viewAllTileTitle: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '700',
        lineHeight: 18,
        paddingHorizontal: 2,
    },
    viewAllTitle: {
        color: colors.text,
        flex: 1,
        fontSize: 17,
        fontWeight: '800',
        textAlign: 'center',
    },
    warningText: {
        color: colors.accent,
    },
});
