import 'dayjs/locale/ar';
import 'dayjs/locale/ca';
import 'dayjs/locale/cs';
import 'dayjs/locale/de';
import 'dayjs/locale/en';
import 'dayjs/locale/es';
import 'dayjs/locale/eu';
import 'dayjs/locale/fa';
import 'dayjs/locale/fi';
import 'dayjs/locale/fr';
import 'dayjs/locale/hu';
import 'dayjs/locale/id';
import 'dayjs/locale/it';
import 'dayjs/locale/ja';
import 'dayjs/locale/ko';
import 'dayjs/locale/nb';
import 'dayjs/locale/nl';
import 'dayjs/locale/pl';
import 'dayjs/locale/pt';
import 'dayjs/locale/pt-br';
import 'dayjs/locale/ru';
import 'dayjs/locale/sl';
import 'dayjs/locale/sr';
import 'dayjs/locale/sv';
import 'dayjs/locale/ta';
import 'dayjs/locale/tr';
import 'dayjs/locale/zh-cn';
import 'dayjs/locale/zh-tw';
export declare const formatDateAbsolute: (key: null | string) => string;
export declare const formatDateAbsoluteUTC: (key: null | string) => string;
export declare const formatPartialIsoDateUTC: (key: null | string) => string;
export declare const formatHrDateTime: (key: null | string) => string;
export declare const formatDateRelative: (key: null | string) => string;
export declare const formatDurationString: (duration: number) => string;
export declare const formatDurationStringShort: (duration: number) => string | string[];
export declare const formatSizeString: (size?: number) => string;
