import './autodiscover';
import './media-fetch';
import './samo';
import './lyrics';
import './player';
import './player-state-broadcast';
import './remote';
import './settings';
import './discord-rpc';
