import { type ComponentType, ImgHTMLAttributes } from 'react';
import { IconBaseProps } from 'react-icons';
export type AppIconSelection = keyof typeof AppIcon;
export declare const AppIcon: {
    readonly add: import("react-icons").IconType;
    readonly album: import("react-icons").IconType;
    readonly alignCenter: import("react-icons").IconType;
    readonly alignLeft: import("react-icons").IconType;
    readonly alignRight: import("react-icons").IconType;
    readonly appWindow: import("react-icons").IconType;
    readonly arrowDown: import("react-icons").IconType;
    readonly arrowDownS: import("react-icons").IconType;
    readonly arrowDownToLine: import("react-icons").IconType;
    readonly arrowLeft: import("react-icons").IconType;
    readonly arrowLeftRight: import("react-icons").IconType;
    readonly arrowLeftS: import("react-icons").IconType;
    readonly arrowLeftToLine: import("react-icons").IconType;
    readonly arrowRight: import("react-icons").IconType;
    readonly arrowRightLast: import("react-icons").IconType;
    readonly arrowRightS: import("react-icons").IconType;
    readonly arrowRightToLine: import("react-icons").IconType;
    readonly arrowUp: import("react-icons").IconType;
    readonly arrowUpS: import("react-icons").IconType;
    readonly arrowUpToLine: import("react-icons").IconType;
    readonly artist: import("react-icons").IconType;
    readonly brandGitHub: import("react-icons").IconType;
    readonly brandLastfm: import("react").ForwardRefExoticComponent<ImgHTMLAttributes<HTMLImageElement> & {
        size?: number | string;
    } & import("react").RefAttributes<HTMLImageElement>>;
    readonly brandListenBrainz: import("react").ForwardRefExoticComponent<ImgHTMLAttributes<HTMLImageElement> & {
        size?: number | string;
    } & import("react").RefAttributes<HTMLImageElement>>;
    readonly brandMusicBrainz: import("react").ForwardRefExoticComponent<ImgHTMLAttributes<HTMLImageElement> & {
        size?: number | string;
    } & import("react").RefAttributes<HTMLImageElement>>;
    readonly brandQobuz: import("react").ForwardRefExoticComponent<ImgHTMLAttributes<HTMLImageElement> & {
        size?: number | string;
    } & import("react").RefAttributes<HTMLImageElement>>;
    readonly brandSpotify: import("react").ForwardRefExoticComponent<ImgHTMLAttributes<HTMLImageElement> & {
        size?: number | string;
    } & import("react").RefAttributes<HTMLImageElement>>;
    readonly cache: import("react-icons").IconType;
    readonly check: import("react-icons").IconType;
    readonly clipboardCopy: import("react-icons").IconType;
    readonly collection: import("react-icons").IconType;
    readonly delete: import("react-icons").IconType;
    readonly disc: import("react-icons").IconType;
    readonly download: import("react-icons").IconType;
    readonly dragHorizontal: import("react-icons").IconType;
    readonly dragVertical: import("react-icons").IconType;
    readonly dropdown: import("react-icons").IconType;
    readonly duration: import("react-icons").IconType;
    readonly edit: import("react-icons").IconType;
    readonly ellipsisHorizontal: import("react-icons").IconType;
    readonly ellipsisVertical: import("react-icons").IconType;
    readonly emptyAlbumImage: import("react-icons").IconType;
    readonly emptyArtistImage: import("react-icons").IconType;
    readonly emptyGenreImage: import("react-icons").IconType;
    readonly emptyImage: import("react-icons").IconType;
    readonly emptyPlaylistImage: import("react-icons").IconType;
    readonly emptySongImage: import("react-icons").IconType;
    readonly error: import("react-icons").IconType;
    readonly expand: import("react-icons").IconType;
    readonly externalLink: import("react-icons").IconType;
    readonly favorite: import("react-icons").IconType;
    readonly fileJson: import("react-icons").IconType;
    readonly filter: import("react-icons").IconType;
    readonly folder: import("react-icons").IconType;
    readonly genre: import("react-icons").IconType;
    readonly goToItem: import("react-icons").IconType;
    readonly hash: import("react-icons").IconType;
    readonly home: import("react-icons").IconType;
    readonly image: import("react-icons").IconType;
    readonly info: import("react-icons").IconType;
    readonly itemAlbum: import("react-icons").IconType;
    readonly itemSong: import("react-icons").IconType;
    readonly json: import("react-icons").IconType;
    readonly keyboard: import("react-icons").IconType;
    readonly lastPlayed: import("react-icons").IconType;
    readonly layoutDetail: import("react-icons").IconType;
    readonly layoutGrid: import("react-icons").IconType;
    readonly layoutList: import("react-icons").IconType;
    readonly layoutPanelBottom: import("react-icons").IconType;
    readonly layoutPanelRight: import("react-icons").IconType;
    readonly layoutTable: import("react-icons").IconType;
    readonly library: import("react-icons").IconType;
    readonly list: import("react-icons").IconType;
    readonly listInfinite: import("react-icons").IconType;
    readonly listPaginated: import("react-icons").IconType;
    readonly lock: import("react-icons").IconType;
    readonly lockOpen: import("react-icons").IconType;
    readonly mediaNext: import("react-icons").IconType;
    readonly mediaPause: import("react-icons").IconType;
    readonly mediaPlay: import("react-icons").IconType;
    readonly mediaPlayLast: import("react-icons").IconType;
    readonly mediaPlayNext: import("react-icons").IconType;
    readonly mediaPrevious: import("react-icons").IconType;
    readonly mediaRandom: import("react-icons").IconType;
    readonly mediaRepeat: import("react-icons").IconType;
    readonly mediaRepeatOne: import("react-icons").IconType;
    readonly mediaSettings: import("react-icons").IconType;
    readonly mediaShuffle: import("react-icons").IconType;
    readonly mediaSpeed: import("react-icons").IconType;
    readonly mediaStepBackward: import("react-icons").IconType;
    readonly mediaStepForward: import("react-icons").IconType;
    readonly mediaStop: import("react-icons").IconType;
    readonly menu: import("react-icons").IconType;
    readonly metadata: import("react-icons").IconType;
    readonly microphone: import("react-icons").IconType;
    readonly minus: import("react-icons").IconType;
    readonly mouseLeftClick: import("react-icons").IconType;
    readonly mouseRightClick: import("react-icons").IconType;
    readonly panelRightClose: import("react-icons").IconType;
    readonly panelRightOpen: import("react-icons").IconType;
    readonly pin: import("react-icons").IconType;
    readonly playlist: import("react-icons").IconType;
    readonly playlistAdd: import("react-icons").IconType;
    readonly playlistDelete: import("react-icons").IconType;
    readonly plus: import("react-icons").IconType;
    readonly queryBuilder: import("react-icons").IconType;
    readonly queue: import("react-icons").IconType;
    readonly radio: import("react-icons").IconType;
    readonly refresh: import("react-icons").IconType;
    readonly remove: import("react-icons").IconType;
    readonly save: import("react-icons").IconType;
    readonly search: import("react-icons").IconType;
    readonly server: import("react-icons").IconType;
    readonly settings: import("react-icons").IconType;
    readonly settings2: import("react-icons").IconType;
    readonly share: import("react-icons").IconType;
    readonly signIn: import("react-icons").IconType;
    readonly signOut: import("react-icons").IconType;
    readonly sleepTimer: import("react-icons").IconType;
    readonly sleepTimerOff: import("react-icons").IconType;
    readonly sort: import("react-icons").IconType;
    readonly sortAsc: import("react-icons").IconType;
    readonly sortDesc: import("react-icons").IconType;
    readonly spinner: import("react-icons").IconType;
    readonly square: import("react-icons").IconType;
    readonly squareCheck: import("react-icons").IconType;
    readonly star: import("react-icons").IconType;
    readonly success: import("react-icons").IconType;
    readonly themeDark: import("react-icons").IconType;
    readonly themeLight: import("react-icons").IconType;
    readonly track: import("react-icons").IconType;
    readonly unfavorite: import("react-icons").IconType;
    readonly unpin: import("react-icons").IconType;
    readonly upload: import("react-icons").IconType;
    readonly uploadImage: import("react-icons").IconType;
    readonly user: import("react-icons").IconType;
    readonly userManage: import("react-icons").IconType;
    readonly visibility: import("react-icons").IconType;
    readonly visibilityOff: import("react-icons").IconType;
    readonly volumeMax: import("react-icons").IconType;
    readonly volumeMute: import("react-icons").IconType;
    readonly volumeNormal: import("react-icons").IconType;
    readonly warn: import("react-icons").IconType;
    readonly wifiOff: import("react-icons").IconType;
    readonly wifiOn: import("react-icons").IconType;
    readonly x: import("react-icons").IconType;
    readonly xCircle: import("react-icons").IconType;
};
export interface IconProps extends Omit<IconBaseProps, 'color' | 'fill' | 'size'> {
    animate?: 'pulse' | 'spin';
    color?: IconColor;
    fill?: IconColor;
    icon: keyof typeof AppIcon;
    size?: '2xl' | '3xl' | '4xl' | '5xl' | 'lg' | 'md' | 'sm' | 'xl' | 'xs' | number | string;
}
type IconColor = 'contrast' | 'default' | 'error' | 'favorite' | 'info' | 'inherit' | 'muted' | 'primary' | 'success' | 'warn';
export declare const Icon: import("react").NamedExoticComponent<IconProps & import("react").RefAttributes<HTMLDivElement>>;
export declare const MotionIcon: ComponentType;
export {};
