import { IpcRendererEvent } from 'electron';
import { PlayerData } from '/@/shared/types/domain-types';
export declare const mpvPlayer: {
    autoNext: (url?: string) => void;
    cleanup: () => Promise<any>;
    currentTime: () => void;
    getAudioDevices: () => Promise<any>;
    getCurrentTime: () => Promise<any>;
    getMetadata: () => Promise<any>;
    getStreamMetadata: (streamUrl?: string) => Promise<any>;
    initialize: (data: {
        extraParameters?: string[];
        properties?: Record<string, any>;
    }) => Promise<any>;
    isRunning: () => Promise<any>;
    mute: (mute: boolean) => void;
    next: () => void;
    pause: () => void;
    play: () => void;
    previous: () => void;
    quit: () => void;
    restart: (data: {
        binaryPath?: string;
        extraParameters?: string[];
        properties?: Record<string, any>;
    }) => Promise<any>;
    seek: (seconds: number) => void;
    seekTo: (seconds: number) => void;
    setProperties: (data: Record<string, any>) => void;
    setQueue: (current?: string, next?: string, pause?: boolean) => void;
    setQueueNext: (url?: string) => void;
    stop: () => void;
    updateMetadata: (data: PlayerData) => void;
    volume: (value: number) => void;
};
export declare const mpvPlayerListener: {
    rendererAutoNext: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
    rendererCurrentTime: (cb: (event: IpcRendererEvent, data: number) => void) => void;
    rendererError: (cb: (event: IpcRendererEvent, data: string) => void) => void;
    rendererNext: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
    rendererPause: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
    rendererPlay: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
    rendererPlayerFallback: (cb: (event: IpcRendererEvent, data: boolean) => void) => void;
    rendererPlayPause: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
    rendererPrevious: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
    rendererQuit: (cb: (event: IpcRendererEvent) => void) => void;
    rendererSkipBackward: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
    rendererSkipForward: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
    rendererStop: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
    rendererToggleRepeat: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
    rendererToggleShuffle: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
    rendererVolumeDown: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
    rendererVolumeMute: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
    rendererVolumeUp: (cb: (event: IpcRendererEvent, data: PlayerData) => void) => void;
};
export type MpvPLayer = typeof mpvPlayer;
export type MpvPlayerListener = typeof mpvPlayerListener;
