import { SelectProps } from '/@/shared/components/select/select';
import { SliderProps } from '/@/shared/components/slider/slider';
export declare const useUpdateAudioMotionAnalyzer: () => {
    updateProperty: <K extends ("opacity" | "mode" | "radius" | "alphaBars" | "ansiBands" | "barSpace" | "channelLayout" | "gradient" | "colorMode" | "customGradients" | "fadePeaks" | "fftSize" | "fillAlpha" | "frequencyScale" | "gravity" | "ledBars" | "linearAmplitude" | "linearBoost" | "lineWidth" | "loRes" | "lumiBars" | "maxDecibels" | "maxFPS" | "maxFreq" | "minDecibels" | "minFreq" | "mirror" | "noteLabels" | "outlineBars" | "peakFadeTime" | "peakHoldTime" | "peakLine" | "presets" | "radial" | "radialInvert" | "reflexAlpha" | "reflexBright" | "reflexFit" | "reflexRatio" | "roundBars" | "showFPS" | "showPeaks" | "showScaleX" | "showScaleY" | "smoothing" | "spinSpeed" | "splitGradient" | "trueLeds" | "volume" | "weightingFilter") | ("gradientLeft" | "gradientRight")>(property: K, value: {
        opacity: number;
        mode: number;
        radius: number;
        alphaBars: boolean;
        ansiBands: boolean;
        barSpace: number;
        channelLayout: "single" | "dual-combined" | "dual-horizontal" | "dual-vertical";
        gradient: string;
        colorMode: "gradient" | "bar-index" | "bar-level";
        customGradients: {
            name: string;
            colorStops: {
                color: string;
                level?: number | undefined;
                levelEnabled?: boolean | undefined;
                pos?: number | undefined;
                positionEnabled?: boolean | undefined;
            }[];
            dir?: string | undefined;
        }[];
        fadePeaks: boolean;
        fftSize: number;
        fillAlpha: number;
        frequencyScale: "linear" | "bark" | "log" | "mel";
        gravity: number;
        ledBars: boolean;
        linearAmplitude: boolean;
        linearBoost: number;
        lineWidth: number;
        loRes: boolean;
        lumiBars: boolean;
        maxDecibels: number;
        maxFPS: number;
        maxFreq: number;
        minDecibels: number;
        minFreq: number;
        mirror: number;
        noteLabels: boolean;
        outlineBars: boolean;
        peakFadeTime: number;
        peakHoldTime: number;
        peakLine: boolean;
        presets: {
            id: string;
            name: string;
            value?: any;
        }[];
        radial: boolean;
        radialInvert: boolean;
        reflexAlpha: number;
        reflexBright: number;
        reflexFit: boolean;
        reflexRatio: number;
        roundBars: boolean;
        showFPS: boolean;
        showPeaks: boolean;
        showScaleX: boolean;
        showScaleY: boolean;
        smoothing: number;
        spinSpeed: number;
        splitGradient: boolean;
        trueLeds: boolean;
        volume: number;
        weightingFilter: "" | "A" | "B" | "C" | "D" | "Z";
        gradientLeft?: string | undefined;
        gradientRight?: string | undefined;
    }[K]) => void;
    visualizer: {
        type: "audiomotionanalyzer" | "butterchurn";
        audiomotionanalyzer: {
            opacity: number;
            mode: number;
            radius: number;
            alphaBars: boolean;
            ansiBands: boolean;
            barSpace: number;
            channelLayout: "single" | "dual-combined" | "dual-horizontal" | "dual-vertical";
            gradient: string;
            colorMode: "gradient" | "bar-index" | "bar-level";
            customGradients: {
                name: string;
                colorStops: {
                    color: string;
                    level?: number | undefined;
                    levelEnabled?: boolean | undefined;
                    pos?: number | undefined;
                    positionEnabled?: boolean | undefined;
                }[];
                dir?: string | undefined;
            }[];
            fadePeaks: boolean;
            fftSize: number;
            fillAlpha: number;
            frequencyScale: "linear" | "bark" | "log" | "mel";
            gravity: number;
            ledBars: boolean;
            linearAmplitude: boolean;
            linearBoost: number;
            lineWidth: number;
            loRes: boolean;
            lumiBars: boolean;
            maxDecibels: number;
            maxFPS: number;
            maxFreq: number;
            minDecibels: number;
            minFreq: number;
            mirror: number;
            noteLabels: boolean;
            outlineBars: boolean;
            peakFadeTime: number;
            peakHoldTime: number;
            peakLine: boolean;
            presets: {
                id: string;
                name: string;
                value?: any;
            }[];
            radial: boolean;
            radialInvert: boolean;
            reflexAlpha: number;
            reflexBright: number;
            reflexFit: boolean;
            reflexRatio: number;
            roundBars: boolean;
            showFPS: boolean;
            showPeaks: boolean;
            showScaleX: boolean;
            showScaleY: boolean;
            smoothing: number;
            spinSpeed: number;
            splitGradient: boolean;
            trueLeds: boolean;
            volume: number;
            weightingFilter: "" | "A" | "B" | "C" | "D" | "Z";
            gradientLeft?: string | undefined;
            gradientRight?: string | undefined;
        };
        butterchurn: {
            opacity: number;
            maxFPS: number;
            blendTime: number;
            cyclePresets: boolean;
            cycleTime: number;
            ignoredPresets: string[];
            includeAllPresets: boolean;
            randomizeNextPreset: boolean;
            selectedPresets: string[];
            currentPreset?: string | undefined;
        };
    };
};
export declare const useUpdateButterchurn: () => {
    updateProperty: <K extends "currentPreset" | ("opacity" | "maxFPS" | "blendTime" | "cyclePresets" | "cycleTime" | "ignoredPresets" | "includeAllPresets" | "randomizeNextPreset" | "selectedPresets")>(property: K, value: {
        opacity: number;
        maxFPS: number;
        blendTime: number;
        cyclePresets: boolean;
        cycleTime: number;
        ignoredPresets: string[];
        includeAllPresets: boolean;
        randomizeNextPreset: boolean;
        selectedPresets: string[];
        currentPreset?: string | undefined;
    }[K]) => void;
    visualizer: {
        type: "audiomotionanalyzer" | "butterchurn";
        audiomotionanalyzer: {
            opacity: number;
            mode: number;
            radius: number;
            alphaBars: boolean;
            ansiBands: boolean;
            barSpace: number;
            channelLayout: "single" | "dual-combined" | "dual-horizontal" | "dual-vertical";
            gradient: string;
            colorMode: "gradient" | "bar-index" | "bar-level";
            customGradients: {
                name: string;
                colorStops: {
                    color: string;
                    level?: number | undefined;
                    levelEnabled?: boolean | undefined;
                    pos?: number | undefined;
                    positionEnabled?: boolean | undefined;
                }[];
                dir?: string | undefined;
            }[];
            fadePeaks: boolean;
            fftSize: number;
            fillAlpha: number;
            frequencyScale: "linear" | "bark" | "log" | "mel";
            gravity: number;
            ledBars: boolean;
            linearAmplitude: boolean;
            linearBoost: number;
            lineWidth: number;
            loRes: boolean;
            lumiBars: boolean;
            maxDecibels: number;
            maxFPS: number;
            maxFreq: number;
            minDecibels: number;
            minFreq: number;
            mirror: number;
            noteLabels: boolean;
            outlineBars: boolean;
            peakFadeTime: number;
            peakHoldTime: number;
            peakLine: boolean;
            presets: {
                id: string;
                name: string;
                value?: any;
            }[];
            radial: boolean;
            radialInvert: boolean;
            reflexAlpha: number;
            reflexBright: number;
            reflexFit: boolean;
            reflexRatio: number;
            roundBars: boolean;
            showFPS: boolean;
            showPeaks: boolean;
            showScaleX: boolean;
            showScaleY: boolean;
            smoothing: number;
            spinSpeed: number;
            splitGradient: boolean;
            trueLeds: boolean;
            volume: number;
            weightingFilter: "" | "A" | "B" | "C" | "D" | "Z";
            gradientLeft?: string | undefined;
            gradientRight?: string | undefined;
        };
        butterchurn: {
            opacity: number;
            maxFPS: number;
            blendTime: number;
            cyclePresets: boolean;
            cycleTime: number;
            ignoredPresets: string[];
            includeAllPresets: boolean;
            randomizeNextPreset: boolean;
            selectedPresets: string[];
            currentPreset?: string | undefined;
        };
    };
};
type ButterchurnPresetOption = {
    label: string;
    value: string;
};
export declare const useButterchurnPresetOptions: () => ButterchurnPresetOption[];
export declare const VisualizerSelect: (props: SelectProps) => import("react/jsx-runtime").JSX.Element;
export declare const VisualizerSlider: (props: SliderProps & {
    label?: React.ReactNode;
}) => import("react/jsx-runtime").JSX.Element;
export declare const VisualizerToggle: (props: {
    disabled?: boolean;
    label: string;
    onChange: (value: boolean) => void;
    value: boolean;
}) => import("react/jsx-runtime").JSX.Element;
export {};
