import type { Variants } from 'motion/react';
declare function combine(...variants: Variants[]): Variants;
declare function stagger(variants: Variants, delay?: number): Variants;
export declare const animationVariants: {
    blurIn: Variants;
    combine: typeof combine;
    fadeIn: Variants;
    fadeInDown: Variants;
    fadeInLeft: Variants;
    fadeInRight: Variants;
    fadeInUp: Variants;
    flipHorizontal: Variants;
    flipVertical: Variants;
    scaleY: Variants;
    slideInDown: Variants;
    slideInLeft: Variants;
    slideInRight: Variants;
    slideInUp: Variants;
    stagger: typeof stagger;
    zoomIn: Variants;
    zoomOut: Variants;
};
export {};
