import { ItemGridListRowConfig, ItemTableListColumnConfig } from '/@/renderer/store';
import { TableColumn } from '/@/shared/types/types';
export type DefaultTableColumn = {
    align: 'center' | 'end' | 'start';
    autoSize: boolean;
    isEnabled: boolean;
    label: string;
    pinned: 'left' | 'right' | null;
    value: TableColumn;
    width: number;
};
export declare const SONG_TABLE_COLUMNS: DefaultTableColumn[];
export declare const PLAYLIST_SONG_TABLE_COLUMNS: DefaultTableColumn[];
export declare const ALBUM_TABLE_COLUMNS: DefaultTableColumn[];
export declare const ALBUM_ARTIST_TABLE_COLUMNS: DefaultTableColumn[];
export declare const PLAYLIST_TABLE_COLUMNS: DefaultTableColumn[];
export declare const GENRE_TABLE_COLUMNS: DefaultTableColumn[];
export declare const pickTableColumns: (options: {
    alignCenterColumns?: TableColumn[];
    alignLeftColumns?: TableColumn[];
    alignRightColumns?: TableColumn[];
    autoSizeColumns?: TableColumn[];
    columns: DefaultTableColumn[];
    columnWidths?: Partial<Record<TableColumn, number>>;
    enabledColumns: TableColumn[];
    pickColumns?: TableColumn[];
    pinnedLeftColumns?: TableColumn[];
    pinnedRightColumns?: TableColumn[];
}) => ItemTableListColumnConfig[];
export declare const pickGridRows: (options: Parameters<typeof pickTableColumns>[0]) => ItemGridListRowConfig[];
