import { StyleSheet } from 'react-native';
import { colors } from '../tokens';

/** Hand-drawn glyph primitives (Glyphs.tsx). */
export const glyphStyles = StyleSheet.create({
    castGlyph: {
        borderRadius: 3,
        borderWidth: 1.8,
        height: 18,
        position: 'relative',
        width: 23,
    },
    castGlyphDot: {
        borderRadius: 2,
        bottom: 2,
        height: 4,
        left: 2,
        position: 'absolute',
        width: 4,
    },
    castGlyphWaveLarge: {
        borderBottomLeftRadius: 13,
        borderBottomWidth: 1.8,
        borderLeftWidth: 1.8,
        bottom: 2,
        height: 13,
        left: 2,
        position: 'absolute',
        width: 13,
    },
    castGlyphWaveSmall: {
        borderBottomLeftRadius: 8,
        borderBottomWidth: 1.8,
        borderLeftWidth: 1.8,
        bottom: 2,
        height: 8,
        left: 2,
        position: 'absolute',
        width: 8,
    },
    clearGlyph: {
        alignItems: 'center',
        height: 18,
        justifyContent: 'center',
        position: 'relative',
        width: 18,
    },
    clearGlyphStroke: {
        borderRadius: 999,
        height: 2,
        position: 'absolute',
        width: 14,
    },
    downCaretGlyph: {
        height: 20,
        position: 'relative',
        width: 24,
    },
    downCaretStroke: {
        borderRadius: 999,
        height: 2.4,
        position: 'absolute',
        top: 9,
        width: 13,
    },
    downCaretStrokeLeft: {
        left: 2,
        transform: [{ rotate: '42deg' }],
    },
    downCaretStrokeRight: {
        right: 2,
        transform: [{ rotate: '-42deg' }],
    },
    gearGlyphText: {
        fontSize: 18,
        fontWeight: '700',
        lineHeight: 22,
    },
    moreGlyph: {
        alignItems: 'center',
        height: 24,
        justifyContent: 'center',
        width: 24,
    },
    moreGlyphDot: {
        borderRadius: 999,
        height: 3.2,
        marginVertical: 1.5,
        width: 3.2,
    },
    pauseGlyph: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 4,
        justifyContent: 'center',
    },
    pauseGlyphBar: {
        borderRadius: 2,
        height: '100%',
        width: 5,
    },
    playCircleGlyph: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        borderRadius: 999,
        height: 32,
        justifyContent: 'center',
        width: 32,
    },
    playGlyph: {
        borderBottomColor: 'transparent',
        borderTopColor: 'transparent',
        height: 0,
        marginLeft: 2,
        width: 0,
    },
    searchGlyph: {
        height: 22,
        position: 'relative',
        width: 22,
    },
    searchGlyphCircle: {
        borderRadius: 7,
        borderWidth: 2,
        height: 14,
        left: 2,
        position: 'absolute',
        top: 2,
        width: 14,
    },
    searchGlyphHandle: {
        borderRadius: 999,
        bottom: 3,
        height: 2,
        position: 'absolute',
        right: 2,
        transform: [{ rotate: '45deg' }],
        width: 8,
    },
    shuffleGlyph: {
        height: 18,
        position: 'relative',
        width: 20,
    },
    shuffleGlyphArrow: {
        borderLeftColor: 'transparent',
        borderLeftWidth: 4,
        borderRightColor: 'transparent',
        borderRightWidth: 4,
        borderTopWidth: 5,
        height: 0,
        position: 'absolute',
        right: 0,
        width: 0,
    },
    shuffleGlyphLine: {
        borderRadius: 999,
        height: 2,
        left: 0,
        position: 'absolute',
        top: 4,
        width: 14,
    },
    skipGlyph: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
    },
    skipGlyphBar: {
        borderRadius: 2,
        height: 17,
        width: 3,
    },
    skipGlyphTriangle: {
        borderBottomColor: 'transparent',
        borderTopColor: 'transparent',
        height: 0,
        width: 0,
    },
    skipGlyphTriangles: {
        flexDirection: 'row',
        gap: 1,
    },
    sortGlyph: {
        alignItems: 'flex-start',
        gap: 3,
        width: 15,
    },
    sortGlyphLine: {
        borderRadius: 999,
        height: 2,
    },
    starGlyph: {
        alignItems: 'center',
        height: 24,
        justifyContent: 'center',
        width: 24,
    },
    starGlyphText: {
        fontSize: 18,
        lineHeight: 22,
    },
    stepGlyphText: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '900',
    },
});
