import { StyleSheet } from 'react-native';
import {
    HOME_EDGE_PADDING,
    SCROLL_CONTENT_BOTTOM_INSET,
    SCREEN_WIDTH,
    STATUS_BAR_INSET,
} from '../layout';
import { colors, elevation, fonts, radii, spacing } from '../tokens';

/** Media detail overlay: heroes, track rows, book info. */
export const mediaDetailStyles = StyleSheet.create({
    albumHero: {
        alignItems: 'center',
        marginBottom: spacing.lg,
        marginTop: spacing.lg,
        position: 'relative',
    },
    albumHeroActions: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
    },
    albumHeroActionsBar: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: spacing.md,
        width: '100%',
    },
    /**
     * Wrapper for one choreographed stage of the hero (see Choreographed).
     *
     * `albumHero` is a centred column, so a bare wrapper would shrink to fit
     * its content — and any child sized `width: '100%'` (the meta block, the
     * actions bar) would then resolve that percentage against a width derived
     * from itself and collapse. Stretching the wrapper preserves the full-width
     * box those children were written against; re-centring inside it preserves
     * what the parent's alignItems was doing for everything else.
     */
    albumHeroStage: {
        alignItems: 'center',
        alignSelf: 'stretch',
    },
    albumHeroArtwork: {
        aspectRatio: 1,
        backgroundColor: colors.surface,
        borderRadius: radii.sm,
        width: Math.min(SCREEN_WIDTH - HOME_EDGE_PADDING * 2 - 40, 360),
        ...elevation.raised,
    },
    albumHeroArtworkFallback: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    albumHeroArtworkWrap: {
        marginBottom: spacing.md,
        position: 'relative',
    },
    albumHeroBadgeRow: {
        alignItems: 'center',
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        justifyContent: 'center',
        marginBottom: 6,
    },
    albumHeroEyebrow: {
        color: colors.accent,
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 1.4,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    albumHeroGlyphButton: {
        alignItems: 'center',
        borderRadius: 999,
        height: 44,
        justifyContent: 'center',
        width: 44,
    },
    albumHeroLeftActions: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
    },
    albumHeroMeta: {
        alignItems: 'center',
        marginTop: spacing.xs,
        width: '100%',
    },
    albumHeroMetaLine: {
        color: colors.muted,
        fontSize: 13,
        fontFamily: fonts.mono,
        fontWeight: '600',
        lineHeight: 18,
        textAlign: 'center',
    },
    albumHeroMetaRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.md,
        marginTop: spacing.xs,
        width: '100%',
    },
    albumHeroMetaText: {
        flex: 1,
        minWidth: 0,
    },
    albumHeroPlayButton: {
        backgroundColor: colors.accent,
        height: 52,
        width: 52,
    },
    albumHeroTitle: {
        color: colors.text,
        fontSize: 26,
        fontFamily: fonts.heading,
        letterSpacing: 0,
        lineHeight: 30,
        marginTop: spacing.sm,
        textAlign: 'center',
    },
    albumHeroYear: {
        color: colors.muted,
        fontSize: 14,
        fontFamily: fonts.mono,
        fontWeight: '600',
        lineHeight: 20,
        marginTop: spacing.xs,
        textAlign: 'center',
    },
    albumDiscHeader: {
        borderTopColor: 'rgba(255,255,255,0.08)',
        borderTopWidth: StyleSheet.hairlineWidth,
        marginTop: spacing.md,
        paddingBottom: spacing.xs,
        paddingTop: spacing.md,
    },
    albumDiscHeaderText: {
        color: colors.accent,
        fontSize: 12,
        fontWeight: '900',
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    albumTrackNumber: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 28,
    },
    albumTrackNumberText: {
        color: colors.muted,
        fontSize: 15,
        fontVariant: ['tabular-nums'],
        fontWeight: '700',
    },
    artistAlbumGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginTop: spacing.md,
    },
    artistAlbumGridArtwork: {
        aspectRatio: 1,
        borderRadius: 6,
        width: '100%',
    },
    artistAlbumGridFallback: {
        alignItems: 'center',
        aspectRatio: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.07)',
        borderRadius: 6,
        justifyContent: 'center',
        width: '100%',
    },
    artistAlbumGridItem: {
        position: 'relative',
        width: '30%',
    },
    artistAlbumGridTitle: {
        color: colors.text,
        fontSize: 12,
        fontWeight: '700',
        marginTop: 5,
    },
    artistBio: {
        color: colors.muted,
        fontSize: 14,
        lineHeight: 20,
    },
    artistBioToggle: {
        color: colors.accent,
        fontSize: 13,
        fontWeight: '700',
        marginTop: spacing.xs,
    },
    bookInfoArtwork: {
        backgroundColor: '#2a2a2c',
        borderRadius: 12,
        height: 188,
        width: 188,
    },
    bookInfoArtworkFallback: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    bookInfoArtworkWrap: {
        alignItems: 'center',
        marginBottom: spacing.lg,
        shadowColor: '#000',
        shadowOffset: { height: 12, width: 0 },
        shadowOpacity: 0.4,
        shadowRadius: 22,
    },
    bookInfoAuthor: {
        color: colors.muted,
        fontSize: 15,
        fontWeight: '600',
        marginTop: 4,
        textAlign: 'center',
    },
    bookInfoBackdrop: {
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.78)',
        bottom: 0,
        flex: 1,
        justifyContent: 'center',
        left: 0,
        paddingHorizontal: spacing.lg,
        position: 'absolute',
        right: 0,
        top: 0,
    },
    bookInfoCloseButton: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        borderRadius: 12,
        marginHorizontal: spacing.lg,
        marginVertical: spacing.md,
        paddingVertical: 14,
    },
    bookInfoCloseLabel: {
        color: colors.text,
        fontSize: 15,
        fontWeight: '800',
        letterSpacing: 0.2,
    },
    bookInfoDescription: {
        color: '#d8d8d8',
        fontSize: 14,
        fontWeight: '400',
        lineHeight: 21,
    },
    bookInfoEmpty: {
        color: colors.muted,
        fontSize: 13,
        marginTop: spacing.md,
        textAlign: 'center',
    },
    bookInfoError: {
        color: '#ff7a6e',
        fontSize: 13,
        fontWeight: '700',
        marginTop: spacing.md,
        textAlign: 'center',
    },
    bookInfoEyebrow: {
        color: colors.accent,
        fontSize: 10,
        fontWeight: '900',
        letterSpacing: 1.4,
        marginBottom: 6,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    bookInfoLoading: {
        marginTop: spacing.lg,
    },
    bookInfoMetadata: {
        alignItems: 'center',
        gap: 2,
        marginBottom: spacing.lg,
        marginTop: spacing.md,
    },
    bookInfoMetadataLine: {
        color: colors.muted,
        fontSize: 12,
        fontFamily: fonts.mono,
        fontWeight: '600',
        letterSpacing: 0.2,
        textAlign: 'center',
    },
    bookInfoScrollContent: {
        padding: spacing.lg,
        paddingBottom: spacing.md,
    },
    bookInfoSectionTitle: {
        color: colors.accent,
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 1.2,
        marginBottom: 8,
        textTransform: 'uppercase',
    },
    bookInfoSheet: {
        backgroundColor: 'rgba(20, 20, 22, 0.985)',
        borderColor: 'rgba(255, 255, 255, 0.07)',
        borderRadius: 22,
        borderWidth: 0.5,
        elevation: 22,
        maxHeight: '82%',
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { height: 18, width: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 30,
        width: '100%',
    },
    bookInfoTitle: {
        color: colors.text,
        fontSize: 22,
        fontFamily: fonts.heading,
        letterSpacing: 0.1,
        lineHeight: 27,
        textAlign: 'center',
    },
    detailArtwork: {
        aspectRatio: 1,
        backgroundColor: colors.surface,
        borderRadius: radii.md,
        width: 132,
        ...elevation.card,
    },
    detailArtworkFallback: {
        alignItems: 'center',
        aspectRatio: 1,
        backgroundColor: colors.surface,
        borderRadius: radii.md,
        justifyContent: 'center',
        width: 132,
    },
    detailArtworkRound: {
        borderRadius: 999,
    },
    detailHero: {
        alignItems: 'flex-start',
        flexDirection: 'row',
        gap: spacing.md,
        marginTop: spacing.lg,
    },
    detailCollapsedActions: {
        alignItems: 'center',
        elevation: 3,
        flexDirection: 'row',
        gap: 10,
        position: 'absolute',
        right: HOME_EDGE_PADDING,
        zIndex: 3,
    },
    detailCollapsedBackButton: {
        alignItems: 'center',
        borderRadius: 999,
        height: 42,
        justifyContent: 'center',
        left: HOME_EDGE_PADDING - 8,
        position: 'absolute',
        width: 42,
        zIndex: 2,
    },
    detailCollapsedBackGlyph: {
        color: colors.text,
        fontSize: 36,
        fontWeight: '300',
        includeFontPadding: false,
        lineHeight: 40,
        marginTop: -2,
    },
    detailCollapsedIconButton: {
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.08)',
        borderRadius: 999,
        height: 42,
        justifyContent: 'center',
        width: 42,
    },
    detailCollapsedPlayButton: {
        alignItems: 'center',
        backgroundColor: colors.accent,
        borderRadius: 999,
        height: 42,
        justifyContent: 'center',
        width: 42,
    },
    detailCollapsedTitle: {
        color: colors.text,
        fontSize: 17,
        fontWeight: '900',
        letterSpacing: 0,
        lineHeight: 21,
        textAlign: 'center',
    },
    detailCollapsedTitleWrap: {
        left: HOME_EDGE_PADDING + 48,
        minWidth: 0,
        position: 'absolute',
        right: HOME_EDGE_PADDING + 112,
    },
    /**
     * The collapsing detail top bar's OUTER box: it starts at physical y=0
     * (the scenes run edge-to-edge) and is tall enough to hold the status bar
     * PLUS the 58dp control row. The backdrop fills this whole box, so the
     * scrolling hero never shows through beside the clock.
     *
     * The row itself is a separate child pinned to the bottom 58dp — the back
     * button / title / actions are absolutely positioned against THAT, never
     * against this box. Centering them in here (what this style used to do,
     * with no status-bar clearance at all) put the back chevron's midline at
     * y=29, i.e. inside the status bar / display cutout: the "back buttons are
     * too high" report. `mediaDetailContent` already reserves
     * `58 + STATUS_BAR_INSET`, so the content below needs no change.
     */
    detailCollapsedTopbar: {
        height: 58 + STATUS_BAR_INSET,
        left: 0,
        position: 'absolute',
        right: 0,
        top: 0,
        zIndex: 20,
    },
    /** The bar's control row — seated BELOW the status bar, never in it. */
    detailCollapsedTopbarRow: {
        alignItems: 'center',
        bottom: 0,
        height: 58,
        justifyContent: 'center',
        left: 0,
        position: 'absolute',
        right: 0,
    },
    detailCollapsedTopbarBackdrop: {
        backgroundColor: 'rgba(0, 0, 0, 0.92)',
        borderBottomColor: 'rgba(255, 255, 255, 0.06)',
        borderBottomWidth: StyleSheet.hairlineWidth,
        bottom: 0,
        left: 0,
        position: 'absolute',
        right: 0,
        top: 0,
    },
    detailHeroActions: {
        alignSelf: 'flex-end',
        flexDirection: 'row',
        gap: spacing.sm,
        justifyContent: 'flex-end',
        marginTop: spacing.md,
    },
    detailHeroText: {
        flex: 1,
    },
    mediaDetailContent: {
        paddingBottom: SCROLL_CONTENT_BOTTOM_INSET,
        paddingHorizontal: HOME_EDGE_PADDING,
        paddingTop: 58 + STATUS_BAR_INSET,
    },
    mediaDetailScreen: {
        backgroundColor: colors.background,
        flex: 1,
    },
    detailPlayPill: {
        alignItems: 'center',
        backgroundColor: colors.accent,
        borderRadius: 999,
        flexDirection: 'row',
        gap: 8,
        height: 44,
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    detailPlayPillText: {
        color: colors.background,
        fontSize: 15,
        fontWeight: '900',
    },
    detailShufflePill: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderColor: 'rgba(255,255,255,0.1)',
        borderRadius: 999,
        borderWidth: 1,
        flexDirection: 'row',
        gap: 8,
        height: 44,
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    detailShufflePillText: {
        color: colors.text,
        fontSize: 15,
        fontWeight: '800',
    },
    detailTitle: {
        color: colors.text,
        fontSize: 24,
        fontFamily: fonts.heading,
        lineHeight: 28,
        marginBottom: spacing.xs,
    },
    detailType: {
        color: colors.accent,
        fontSize: 12,
        fontWeight: '800',
        marginBottom: spacing.xs,
        textTransform: 'capitalize',
    },
    chapterQualityHint: {
        color: colors.muted,
        fontSize: 12,
        fontFamily: fonts.mono,
        fontWeight: '600',
        letterSpacing: 0.2,
        marginBottom: 6,
        marginTop: -2,
    },
    chapterQualityReview: {
        color: colors.accent,
    },
    relatedArtistArtwork: {
        backgroundColor: colors.surface,
        borderRadius: 999,
        height: 112,
        marginBottom: spacing.xs,
        width: 112,
    },
    relatedArtistArtworkFallback: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    relatedArtistTile: {
        alignItems: 'center',
        marginRight: spacing.md,
        width: 112,
    },
    relatedArtistTitle: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '700',
        textAlign: 'center',
    },
    trackArtwork: {
        borderRadius: 6,
        height: 44,
        width: 44,
    },
    trackArtworkFallback: {
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 6,
        height: 44,
        justifyContent: 'center',
        width: 44,
    },
    trackArtworkLetter: {
        color: colors.muted,
        fontSize: 16,
        fontWeight: '700',
    },
    trackMetadataLine: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 6,
        minWidth: 0,
    },
    trackMetadataText: {
        flexShrink: 1,
        minWidth: 0,
    },
    trackRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: spacing.sm,
        minHeight: 62,
        paddingVertical: 9,
    },
    trackText: {
        flex: 1,
        justifyContent: 'center',
        minWidth: 0,
    },
    trackTitle: {
        color: colors.text,
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: 0,
        lineHeight: 21,
        marginBottom: 2,
    },
});
