import { StyleSheet } from 'react-native';

import { colors, fonts, radii } from '../theme/tokens';

/**
 * The TV in the phone's own materials — the same tokens, faces and cover
 * treatment — sized for a screen read from across a room.
 *
 * TV dp are already density-scaled by Android: a 1080p panel is a 960×540dp
 * canvas. Essential chrome stays inside the 5% overscan-safe area.
 */
export const TV_SAFE_Y = 27;
export const TV_SAFE_RIGHT = 48;
/** The collapsed rail: the phone's tab icons, standing on the left edge. */
export const TV_RAIL_WIDTH = 88;
/** The rail with its labels, drawn over the content while it has focus. */
export const TV_RAIL_EXPANDED_WIDTH = 300;
/** Where content starts: the rail plus the seam the focus guide lives on. */
export const TV_CONTENT_LEFT = 104;
export const TV_TILE = 136;
export const TV_TILE_GAP = 20;
/** Room around a row for a focused tile's lift, so it is never clipped. */
export const TV_FOCUS_BLEED = 10;
export const TV_GRID_COLUMNS = 5;
export const TV_TRACK_ROW_HEIGHT = 58;

const FOCUS_INK = colors.background;
const FOCUS_FILL = colors.accentBright;
const QUIET_FILL = 'rgba(255, 255, 255, 0.08)';

export const tvStyles = StyleSheet.create({
    root: { backgroundColor: colors.background, flex: 1 },
    cornerLogo: { position: 'absolute', top: 20, right: 32, width: 26, height: 26, opacity: 0.85 },
    homeFilters: { paddingTop: 30, paddingBottom: 12, paddingLeft: 10, paddingRight: 80 },
    homeScroll: {
        paddingTop: 6,
        paddingLeft: TV_FOCUS_BLEED,
        paddingRight: TV_SAFE_RIGHT,
        paddingBottom: 40,
    },
    railTooltip: {
        position: 'absolute',
        left: 58,
        backgroundColor: colors.surfaceHigh,
        paddingHorizontal: 14,
        paddingVertical: 9,
        borderRadius: 8,
        minWidth: 130,
    },
    railTooltipText: { color: colors.text, fontFamily: fonts.body, fontSize: 14 },
    trackListHeading: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 14,
        marginTop: 28,
    },
    playerTopBar: {
        position: 'absolute',
        top: 27,
        left: 48,
        right: 48,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        zIndex: 1,
    },
    artFocused: {
        borderRadius: 5,
        outlineColor: colors.accentBright,
        outlineWidth: 3,
        outlineOffset: 5,
    },
    transportSelected: {
        backgroundColor: colors.accentSoft,
    },
    hidden: { display: 'none' },
    fill: { ...StyleSheet.absoluteFill },

    // ── Sign in ──────────────────────────────────────────────────────────
    setupFrame: { flex: 1, paddingHorizontal: '5%', paddingVertical: '5%' },
    brand: { color: colors.text, fontFamily: fonts.heading, fontSize: 38, marginBottom: 16 },
    // Sign-in is laid out across the screen, not down it: stacked, the brand
    // alone took a third of the height and pushed the code screen's buttons to
    // the bottom edge.
    setup: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 48 },
    setupIntro: { width: 280 },
    setupPanel: { alignSelf: 'stretch', flex: 1 },
    setupContent: { flexGrow: 1, gap: 18, justifyContent: 'center', paddingVertical: 8 },
    pairing: { alignItems: 'center', flexDirection: 'row', gap: 24 },
    pairingCopy: { flex: 1, gap: 8 },
    pairingCode: { color: colors.text, fontFamily: fonts.monoBold, fontSize: 38, letterSpacing: 5 },
    pairingUrl: { color: colors.text, fontFamily: fonts.mono },

    // ── Type ─────────────────────────────────────────────────────────────
    heading: {
        color: colors.text,
        fontFamily: fonts.heading,
        fontSize: 30,
        letterSpacing: -0.5,
        marginBottom: 10,
    },
    sectionTitle: {
        color: colors.text,
        fontFamily: fonts.heading,
        fontSize: 22,
        letterSpacing: -0.45,
        marginBottom: 2,
    },
    text: { color: colors.text, fontFamily: fonts.body, fontSize: 17 },
    muted: { color: colors.muted, fontFamily: fonts.body, fontSize: 15, lineHeight: 21 },
    error: { color: '#ffb4ab', fontFamily: fonts.body, fontSize: 16 },
    eyebrow: {
        color: colors.accent,
        fontFamily: fonts.monoBold,
        fontSize: 11,
        letterSpacing: 1.4,
        textTransform: 'uppercase',
    },
    scroll: { gap: 18, paddingBottom: 24 },
    row: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 12 },

    // ── Buttons ──────────────────────────────────────────────────────────
    button: {
        alignItems: 'center',
        backgroundColor: QUIET_FILL,
        borderRadius: 10,
        flexDirection: 'row',
        gap: 10,
        justifyContent: 'center',
        minHeight: 44,
        paddingHorizontal: 22,
    },
    buttonPrimary: { backgroundColor: 'rgba(255, 255, 255, 0.16)' },
    buttonSelected: { backgroundColor: colors.surfaceHigh },
    buttonFocused: {
        backgroundColor: FOCUS_FILL,
        outlineColor: FOCUS_FILL,
        outlineWidth: 2,
        outlineOffset: 2,
    },
    quietButton: { backgroundColor: 'transparent', minHeight: 38, paddingHorizontal: 16 },
    buttonText: { color: colors.text, fontFamily: fonts.body, fontSize: 16, fontWeight: '700' },
    buttonTextPrimary: { color: colors.text },
    buttonTextFocused: { color: FOCUS_INK },
    iconButton: { minHeight: 48, paddingHorizontal: 0, width: 48 },
    disabled: { opacity: 0.4 },

    // ── Fields ───────────────────────────────────────────────────────────
    field: { gap: 6 },
    input: {
        backgroundColor: colors.panel,
        borderColor: colors.borderStrong,
        borderRadius: 10,
        borderWidth: 3,
        color: colors.text,
        fontFamily: fonts.body,
        fontSize: 20,
        minHeight: 50,
        padding: 10,
    },
    inputFocused: { backgroundColor: colors.surfaceHigh, borderColor: FOCUS_FILL },
    placeholder: { color: colors.faint },

    // ── Rail ─────────────────────────────────────────────────────────────
    rail: {
        bottom: 0,
        left: 0,
        paddingBottom: TV_SAFE_Y,
        paddingLeft: 24,
        paddingRight: 16,
        paddingTop: 48,
        gap: 6,
        position: 'absolute',
        top: 0,
        width: TV_RAIL_WIDTH,
        zIndex: 20,
    },
    railBackdrop: {
        bottom: 0,
        left: 0,
        position: 'absolute',
        top: 0,
        width: TV_RAIL_EXPANDED_WIDTH + 60,
        zIndex: 19,
    },
    railBrand: {
        color: colors.text,
        fontFamily: fonts.heading,
        fontSize: 21,
        height: 34,
        letterSpacing: -0.4,
        marginBottom: 14,
        marginLeft: 3,
    },
    railGroup: { gap: 6 },
    railFooter: { gap: 6, marginTop: 'auto' },
    railItem: {
        alignItems: 'center',
        height: 48,
        justifyContent: 'center',
        width: 48,
    },
    /** The highlight behind an item: its own 48dp box while collapsed, the
     *  width of the open rail while expanded — drawn past the focusable box. */
    railPill: {
        borderRadius: radii.md,
        bottom: 0,
        left: 0,
        position: 'absolute',
        top: 0,
        width: 48,
    },
    railPillExpanded: { width: TV_RAIL_EXPANDED_WIDTH - 36 - 20 },
    railPillFocused: { backgroundColor: FOCUS_FILL },
    railPillSelected: { backgroundColor: QUIET_FILL },
    railIconBox: { alignItems: 'center', height: 32, justifyContent: 'center', width: 32 },
    railLabelBox: {
        bottom: 0,
        justifyContent: 'center',
        left: 60,
        position: 'absolute',
        top: 0,
        width: TV_RAIL_EXPANDED_WIDTH - 36 - 20 - 72,
    },
    railLabel: { color: colors.muted, fontFamily: fonts.body, fontSize: 17 },
    railLabelSelected: { color: colors.text, fontWeight: '700' },
    railLabelFocused: { color: FOCUS_INK, fontWeight: '700' },
    railNowArt: { backgroundColor: colors.surface, borderRadius: 4, height: 32, width: 32 },
    railNowCopy: { gap: 1 },
    railNowTitle: { color: colors.text, fontFamily: fonts.body, fontSize: 15, fontWeight: '700' },
    railNowSubtitle: { color: colors.muted, fontFamily: fonts.mono, fontSize: 12 },
    railNowTitleFocused: { color: FOCUS_INK },
    /** Collapsed, the only sign something is playing: a dot on the cover. */
    railNowDot: {
        backgroundColor: colors.accentBright,
        borderColor: colors.background,
        borderRadius: 5,
        borderWidth: 2,
        height: 10,
        position: 'absolute',
        right: -4,
        top: -4,
        width: 10,
    },
    guide: {
        bottom: 0,
        left: TV_RAIL_WIDTH + 4,
        position: 'absolute',
        top: 0,
        width: 2,
    },

    // ── Pages ────────────────────────────────────────────────────────────
    content: { bottom: 0, left: TV_CONTENT_LEFT, position: 'absolute', right: 0, top: 0 },
    page: { ...StyleSheet.absoluteFill },
    pageScroll: {
        paddingBottom: 48,
        paddingLeft: TV_FOCUS_BLEED,
        paddingRight: TV_SAFE_RIGHT,
        paddingTop: 48,
    },
    pageHeader: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 14,
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    pageTitle: {
        color: colors.text,
        fontFamily: fonts.heading,
        fontSize: 30,
        letterSpacing: -0.6,
    },
    emptyText: {
        color: colors.muted,
        fontFamily: fonts.body,
        fontSize: 16,
        lineHeight: 23,
        marginTop: 8,
        maxWidth: 560,
    },
    pills: { flexDirection: 'row', gap: 8, marginBottom: 12 },
    pill: {
        alignItems: 'center',
        backgroundColor: 'transparent',
        borderRadius: 8,
        justifyContent: 'center',
        minHeight: 36,
        paddingHorizontal: 18,
    },
    pillActive: { backgroundColor: colors.surfaceHigh },
    pillFocused: { backgroundColor: FOCUS_FILL, transform: [{ scale: 1.06 }] },
    pillText: { color: colors.muted, fontFamily: fonts.body, fontSize: 15, fontWeight: '600' },
    pillTextActive: { color: colors.text },

    // ── Shelves and tiles ────────────────────────────────────────────────
    shelf: { marginBottom: 24 },
    shelfScroll: { marginHorizontal: -TV_FOCUS_BLEED },
    shelfRow: {
        gap: TV_TILE_GAP,
        paddingHorizontal: TV_FOCUS_BLEED,
        paddingVertical: TV_FOCUS_BLEED,
    },
    tile: { width: TV_TILE },
    tileWide: {
        alignItems: 'center',
        backgroundColor: colors.panel,
        borderRadius: 6,
        flexDirection: 'row',
        gap: 14,
        padding: 12,
        width: 330,
    },
    tileArt: {
        backgroundColor: colors.surface,
        borderRadius: 3,
        height: TV_TILE,
        width: TV_TILE,
    },
    tileArtWide: { height: 96, width: 96 },
    tileArtRound: { borderRadius: TV_TILE / 2 },
    tileRing: {
        ...StyleSheet.absoluteFill,
        borderColor: FOCUS_FILL,
        borderRadius: 4,
        borderWidth: 3,
        margin: -4,
    },
    tileRingRound: { borderRadius: TV_TILE / 2 + 4 },
    tileMeta: { alignItems: 'flex-start', flexDirection: 'row', gap: 6 },
    tileMetaText: { flex: 1, minWidth: 0 },
    tileText: { marginTop: 9 },
    tileTextWide: { flex: 1, marginTop: 0 },
    tileTitle: {
        color: colors.text,
        fontFamily: fonts.body,
        fontSize: 14,
        fontWeight: '600',
        lineHeight: 19,
    },
    tileTitleFocused: { color: colors.accentBright },
    tileSubtitle: {
        color: colors.muted,
        fontFamily: fonts.body,
        fontSize: 12,
        lineHeight: 17,
        marginTop: 2,
    },
    centered: { textAlign: 'center' },
    tileProgressTrack: {
        backgroundColor: colors.surfaceHigh,
        borderRadius: 2,
        height: 3,
        marginTop: 7,
        overflow: 'hidden',
    },
    tileProgressFill: { backgroundColor: colors.accent, height: 3 },
    viewAllArt: {
        alignItems: 'center',
        backgroundColor: colors.panel,
        borderColor: colors.border,
        borderRadius: 3,
        borderWidth: 1,
        height: TV_TILE,
        justifyContent: 'center',
        width: TV_TILE,
    },
    viewAllText: { color: colors.text, fontFamily: fonts.body, fontSize: 16, fontWeight: '800' },
    gridRow: {
        flexDirection: 'row',
        gap: TV_TILE_GAP,
        paddingHorizontal: TV_FOCUS_BLEED,
        paddingVertical: 8,
    },

    // ── Home hero ────────────────────────────────────────────────────────
    hero: {
        alignItems: 'center',
        backgroundColor: colors.panel,
        borderColor: colors.border,
        borderRadius: 12,
        borderWidth: 1,
        flexDirection: 'row',
        gap: 28,
        marginBottom: 28,
        minHeight: 196,
        overflow: 'hidden',
        padding: 22,
    },
    heroArt: { backgroundColor: colors.surface, borderRadius: 3, height: 152, width: 152 },
    heroCopy: { flex: 1, gap: 4 },
    heroTitle: {
        color: colors.text,
        fontFamily: fonts.heading,
        fontSize: 28,
        letterSpacing: -0.6,
        lineHeight: 33,
    },
    heroSubtitle: { color: colors.muted, fontFamily: fonts.body, fontSize: 15, lineHeight: 21 },
    heroActions: { flexDirection: 'row', gap: 12, marginTop: 12 },

    // ── Detail ───────────────────────────────────────────────────────────
    detailHeader: {
        alignItems: 'flex-end',
        flexDirection: 'row',
        gap: 28,
        marginBottom: 18,
    },
    detailArt: { backgroundColor: colors.surface, borderRadius: 3, height: 184, width: 184 },
    detailArtRound: { borderRadius: 92 },
    detailCopy: { flex: 1, gap: 6, paddingBottom: 2 },
    detailType: {
        color: colors.muted,
        fontFamily: fonts.monoBold,
        fontSize: 12,
        letterSpacing: 1.6,
        textTransform: 'uppercase',
    },
    detailTitle: {
        color: colors.text,
        fontFamily: fonts.heading,
        fontSize: 32,
        letterSpacing: -0.7,
        lineHeight: 37,
    },
    detailSubtitle: { color: colors.muted, fontFamily: fonts.body, fontSize: 16 },
    detailActions: { flexDirection: 'row', gap: 12, marginTop: 14 },
    detailSectionTitle: { marginBottom: 6, marginTop: 18 },
    track: {
        alignItems: 'center',
        borderRadius: 10,
        flexDirection: 'row',
        gap: 16,
        height: TV_TRACK_ROW_HEIGHT,
        paddingHorizontal: 16,
    },
    trackFocused: { backgroundColor: FOCUS_FILL },
    trackIndex: {
        color: colors.muted,
        fontFamily: fonts.mono,
        fontSize: 14,
        textAlign: 'right',
        width: 32,
    },
    trackCopy: { flex: 1, minWidth: 0 },
    trackTitle: { color: colors.text, fontSize: 16, fontWeight: '700' },
    trackSubtitle: { color: colors.muted, fontFamily: fonts.body, fontSize: 13, marginTop: 3 },
    trackMeta: { color: colors.muted, fontFamily: fonts.mono, fontSize: 13 },
    trackPlaying: { color: colors.accent },
    trackInkFocused: { color: FOCUS_INK },
    discHeader: {
        color: colors.muted,
        fontFamily: fonts.monoBold,
        fontSize: 12,
        letterSpacing: 1.4,
        marginBottom: 4,
        marginTop: 14,
        paddingHorizontal: 16,
        textTransform: 'uppercase',
    },

    // ── Now Playing ──────────────────────────────────────────────────────
    player: { ...StyleSheet.absoluteFill, backgroundColor: colors.background, zIndex: 40 },
    playerBody: {
        alignItems: 'center',
        flex: 1,
        flexDirection: 'row',
        gap: 60,
        paddingHorizontal: 64,
        paddingTop: 96,
        paddingBottom: 86,
    },
    playerArt: { backgroundColor: colors.surface, borderRadius: 4, height: 304, width: 304 },
    playerInfo: { flex: 1, minWidth: 0 },
    playerEyebrow: {
        color: colors.muted,
        fontFamily: fonts.monoBold,
        fontSize: 12,
        letterSpacing: 1.6,
        marginBottom: 8,
        textTransform: 'uppercase',
    },
    playerTitle: {
        color: colors.text,
        fontFamily: fonts.heading,
        fontSize: 34,
        letterSpacing: -0.8,
        lineHeight: 40,
    },
    playerSubtitle: {
        color: '#b8c0ca',
        fontFamily: fonts.body,
        fontSize: 19,
        lineHeight: 26,
        marginTop: 10,
    },
    playerPill: {
        alignSelf: 'flex-start',
        borderColor: colors.borderStrong,
        borderRadius: 6,
        borderWidth: 1,
        marginTop: 14,
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    playerPillDirect: { borderColor: colors.accentLine },
    playerPillText: { color: colors.muted, fontFamily: fonts.monoBold, fontSize: 12 },
    playerPillTextDirect: { color: colors.accentBright },
    playerFooter: {
        position: 'absolute',
        bottom: 27,
        left: 64,
        right: 64,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 24,
        borderTopColor: colors.borderStrong,
        borderTopWidth: 1,
        paddingTop: 12,
    },
    playerStatus: {
        color: colors.muted,
        fontFamily: fonts.body,
        fontSize: 13,
        flex: 1,
    },
    seek: {
        borderRadius: 12,
        marginHorizontal: -12,
        marginTop: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
    },
    seekFocused: { backgroundColor: QUIET_FILL, outlineColor: colors.accentLine, outlineWidth: 2 },
    seekTrack: {
        backgroundColor: 'rgba(255, 255, 255, 0.18)',
        borderRadius: 3,
        height: 6,
        overflow: 'hidden',
    },
    seekFill: { backgroundColor: colors.text, height: 6 },
    seekTimes: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
    seekTime: { color: colors.muted, fontFamily: fonts.mono, fontSize: 13 },
    seekHint: { color: colors.muted, fontFamily: fonts.body, fontSize: 13 },
    transport: {
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 18,
        marginTop: 14,
    },
    transportButton: {
        alignItems: 'center',
        backgroundColor: 'transparent',
        borderRadius: 24,
        height: 48,
        justifyContent: 'center',
        width: 48,
    },
    transportPrimary: {
        backgroundColor: colors.text,
        borderRadius: 34,
        height: 68,
        width: 68,
    },
    transportFocused: {
        backgroundColor: FOCUS_FILL,
        outlineColor: FOCUS_FILL,
        outlineWidth: 2,
        outlineOffset: 3,
    },
    transportPrimaryFocused: {
        outlineColor: colors.accentBright,
        outlineWidth: 2,
        outlineOffset: 5,
    },
    transportSecondary: { flexDirection: 'row', justifyContent: 'center', gap: 20 },
    transportDot: {
        position: 'absolute',
        bottom: 5,
        width: 4,
        height: 4,
        borderRadius: 2,
        backgroundColor: colors.text,
    },
    transportDotFocused: { backgroundColor: colors.background },
    queuePanel: {
        backgroundColor: 'rgba(14, 15, 19, 0.6)',
        borderRadius: radii.lg,
        paddingHorizontal: 14,
        paddingVertical: 16,
        width: 304,
        height: 340,
        flexGrow: 0,
    },
    queueTitle: { marginBottom: 8, paddingHorizontal: 8 },
    queueRow: {
        alignItems: 'center',
        borderRadius: 10,
        flexDirection: 'row',
        gap: 12,
        height: 56,
        paddingHorizontal: 8,
    },
    queueArt: { backgroundColor: colors.surface, borderRadius: 3, height: 40, width: 40 },
    queueHeader: {
        color: colors.muted,
        fontFamily: fonts.monoBold,
        fontSize: 11,
        letterSpacing: 1.4,
        marginBottom: 4,
        marginTop: 10,
        paddingHorizontal: 8,
        textTransform: 'uppercase',
    },

    // ── Menu (long press) ────────────────────────────────────────────────
    menuBackdrop: {
        ...StyleSheet.absoluteFill,
        backgroundColor: 'rgba(8, 9, 12, 0.66)',
        zIndex: 60,
    },
    menuPanel: {
        backgroundColor: colors.surface,
        bottom: 0,
        paddingHorizontal: 26,
        paddingVertical: 34,
        position: 'absolute',
        right: 0,
        top: 0,
        width: 390,
    },
    menuHeader: { alignItems: 'center', flexDirection: 'row', gap: 16, marginBottom: 20 },
    menuArt: { backgroundColor: colors.panel, borderRadius: 3, height: 64, width: 64 },
    menuCopy: { flex: 1, gap: 3 },
    menuTitle: { color: colors.text, fontFamily: fonts.heading, fontSize: 20, lineHeight: 24 },
    menuSubtitle: { color: colors.muted, fontFamily: fonts.mono, fontSize: 12.5 },
    menuItem: {
        alignItems: 'center',
        borderRadius: 12,
        flexDirection: 'row',
        gap: 16,
        minHeight: 50,
        paddingHorizontal: 16,
    },
    menuItemFocused: { backgroundColor: FOCUS_FILL },
    menuLabel: { color: colors.text, flexShrink: 1, fontFamily: fonts.body, fontSize: 17 },
    menuLabelDestructive: { color: '#ff7a6e' },
    menuFeedback: {
        color: colors.accentBright,
        fontFamily: fonts.body,
        fontSize: 15,
        marginTop: 16,
        paddingHorizontal: 16,
    },

    // ── Toast ────────────────────────────────────────────────────────────
    toast: {
        alignSelf: 'center',
        backgroundColor: colors.surfaceHigh,
        borderRadius: radii.pill,
        bottom: 34,
        paddingHorizontal: 24,
        paddingVertical: 12,
        position: 'absolute',
        zIndex: 80,
    },
    toastText: { color: colors.text, fontFamily: fonts.body, fontSize: 16 },

    // ── Radio ────────────────────────────────────────────────────────────
    radioPageHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 20,
        marginBottom: 20,
    },
    radioSectionLabel: {
        color: colors.muted,
        fontFamily: fonts.body,
        fontSize: 14,
        marginBottom: 12,
    },
    radioCard: {
        backgroundColor: '#191d24',
        borderColor: colors.borderStrong,
        borderRadius: 14,
        borderWidth: 1,
        marginBottom: 28,
        padding: 24,
    },
    radioDeviceHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 24,
        marginBottom: 24,
    },
    radioDeviceLabel: { color: colors.muted, fontFamily: fonts.headingMedium, fontSize: 15 },
    radioHead: { alignItems: 'center', flexDirection: 'row', gap: 30 },
    radioCopy: { flex: 1, minWidth: 0 },
    radioTitle: {
        color: colors.text,
        fontFamily: fonts.heading,
        fontSize: 32,
        letterSpacing: -0.7,
        lineHeight: 38,
    },
    radioMeta: {
        color: '#b8c0ca',
        fontFamily: fonts.body,
        fontSize: 16,
        lineHeight: 23,
        marginTop: 8,
    },
    radioStatus: { color: colors.muted, fontFamily: fonts.body, fontSize: 13, marginTop: 12 },
    radioSleeve: { backgroundColor: colors.surface, borderRadius: 6, height: 156, width: 156 },
    radioControls: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 20,
        marginTop: 24,
        paddingTop: 20,
        borderTopWidth: 1,
        borderTopColor: colors.borderStrong,
    },
    radioTransport: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    radioActions: { flexDirection: 'row', gap: 2, marginLeft: 'auto' },
    radioVolumeGroup: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    volumeStep: { backgroundColor: 'transparent', minHeight: 38, width: 36, paddingHorizontal: 0 },
    volumeStepText: { color: colors.text, fontFamily: fonts.body, fontSize: 22 },
    radioVolumeReadout: { width: 48, alignItems: 'center', gap: 7 },
    radioVolumeTrack: {
        backgroundColor: colors.surfaceHigh,
        borderRadius: 2,
        height: 3,
        width: '100%',
        overflow: 'hidden',
    },
    radioVolumeFill: { backgroundColor: colors.accent, height: 3 },
    radioVolumeLabel: { color: colors.muted, fontFamily: fonts.mono, fontSize: 12 },
    radioPanelTitle: { marginTop: 8, marginBottom: 24 },
    radioPanelStatus: {
        color: colors.muted,
        fontFamily: fonts.body,
        fontSize: 14,
        marginBottom: 18,
    },
    radioPanelClose: { marginTop: 18 },
    radioNotice: {
        backgroundColor: colors.panel,
        borderRadius: 14,
        gap: 8,
        marginBottom: 24,
        padding: 28,
    },
    radioFeedback: {
        color: colors.accentBright,
        fontFamily: fonts.body,
        fontSize: 15,
        marginTop: 12,
    },
});
