export const HOME_ARTWORK_PREFETCH_LIMIT = 48;
export const LIBRARY_FULL_COLLECTION_PREFETCH_DELAY_MS = 500;
export const MEDIA_DETAIL_MEMORY_CACHE_LIMIT = 24;
export const MEDIA_DETAIL_MEMORY_TRACK_LIMIT = 300;
export const DEFAULT_SERVER_URL = 'http://';
